// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The audit configuration for Compliance Manager.
public struct AuditConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The list of destinations that can be selected for uploading audit
  /// reports to.
  public var destinations: [AuditConfig.CmEligibleDestination] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AuditConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AuditConfig().with { $0.destinations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let destinations = CodingKeys(stringValue: "destinations")

    static let _knownKeys: Set<Swift.String> = [
      "destinations"
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [AuditConfig.CmEligibleDestination].self, forKey: .destinations)
    {
      self.destinations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.destinations, forKey: .destinations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The destination details where audit reports are
  /// uploaded.
  public struct CmEligibleDestination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Set of options for the report destination location.
    public var cmEligibleDestinations: CmEligibleDestinationsOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CmEligibleDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CmEligibleDestination().with { $0.gcsBucket = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gcsBucket = CodingKeys(stringValue: "gcsBucket")

      static let _knownKeys: Set<Swift.String> = [
        "gcsBucket"
      ]
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var cmEligibleDestinations: CmEligibleDestinationsOneOf? = nil
      let cmEligibleDestinationsCheckAndSet = {
        if cmEligibleDestinations != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'cmEligibleDestinations'"))
        }
        cmEligibleDestinations = $0
      }
      if let gcsBucket = try container.decodeIfPresent(Swift.String.self, forKey: .gcsBucket) {
        try cmEligibleDestinationsCheckAndSet(.gcsBucket(gcsBucket))
      }
      self.cmEligibleDestinations = cmEligibleDestinations
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.cmEligibleDestinations {
        switch choice {
        case .gcsBucket(let value):
          try container.encode(value, forKey: .gcsBucket)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Set of options for the report destination location.
    public enum CmEligibleDestinationsOneOf: Codable, Equatable, Sendable {
      /// The Cloud Storage bucket where audit reports and evidences can be
      /// uploaded. The format is `gs://{bucket_name}`.
      case gcsBucket(Swift.String)
    }

    /// The type URL for `CmEligibleDestination`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig.CmEligibleDestination"`.
    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig.CmEligibleDestination"
    }

    /// Initialize an instance of `CmEligibleDestination` by unpacking from a `GoogleWKT.WKTAny`.
    ///
    /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
    /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig.CmEligibleDestination"`,
    ///   or if deserialization fails.
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }

    /// Packs this `CmEligibleDestination` into a `GoogleWKT.WKTStruct` representation.
    ///
    /// - Throws: An error if serialization fails.
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The type URL for `AuditConfig`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig"
  }

  /// Initialize an instance of `AuditConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.AuditConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `AuditConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
