// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Common Expression Language (CEL) expression that's used to create a rule.
public struct CELExpression: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The logical expression in CEL. The maximum length of the
  /// condition is 1000 characters. For more information, see [CEL
  /// expression](https://cloud.google.com/security-command-center/docs/compliance-manager-write-cel-expressions).
  public var expression: Swift.String = Swift.String()

  /// The criteria of the CEL expression.
  public var criteria: CriteriaOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CELExpression`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CELExpression().with { $0.resourceTypesValues = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let resourceTypesValues = CodingKeys(stringValue: "resourceTypesValues")
    static let expression = CodingKeys(stringValue: "expression")

    static let _knownKeys: Set<Swift.String> = [
      "resourceTypesValues",
      "expression",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .expression) {
      self.expression = value
    }

    var criteria: CriteriaOneOf? = nil
    let criteriaCheckAndSet = {
      if criteria != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'criteria'"))
      }
      criteria = $0
    }
    if let resourceTypesValues = try container.decodeIfPresent(
      StringList.self, forKey: .resourceTypesValues)
    {
      try criteriaCheckAndSet(.resourceTypesValues(resourceTypesValues))
    }
    self.criteria = criteria
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.expression, forKey: .expression)

    if let choice = self.criteria {
      switch choice {
      case .resourceTypesValues(let value):
        try container.encode(value, forKey: .resourceTypesValues)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The criteria of the CEL expression.
  public enum CriteriaOneOf: Codable, Equatable, Sendable {
    /// The resource instance types on which this expression is defined.
    /// The format is `<SERVICE_NAME>/<type>`.
    /// For example: `compute.googleapis.com/Instance`
    indirect case resourceTypesValues(StringList)
  }

  /// The type URL for `CELExpression`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CELExpression"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CELExpression"
  }

  /// Initialize an instance of `CELExpression` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CELExpression"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CELExpression` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
