// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The cloud control report.
public struct CloudControlReport: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the cloud control.
  public var cloudControl: Swift.String = Swift.String()

  /// The display name of the cloud control.
  public var displayName: Swift.String = Swift.String()

  /// The description of the cloud control.
  public var description: Swift.String = Swift.String()

  /// The list of categories for the cloud control.
  public var categories: [Swift.String] = []

  /// The list of similar controls.
  public var similarControls: [SimilarControls] = []

  /// The type of the cloud control.
  public var cloudControlType: CloudControl.Type_ = CloudControl.Type_()

  /// The category of the finding.
  public var findingCategory: Swift.String = Swift.String()

  /// The list of rules that correspond to the cloud control.
  public var rules: [Rule] = []

  /// The severity of the finding.
  public var findingSeverity: Severity = Severity()

  /// The enforcement mode of the cloud control.
  public var enforcementMode: EnforcementMode = EnforcementMode()

  /// The name of the cloud control deployment.
  public var cloudControlDeployment: Swift.String = Swift.String()

  /// The major revision ID of the cloud control.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// The minor revision ID of the cloud control.
  public var minorRevisionId: Swift.Int64 = Swift.Int64()

  /// The major revision IDs of the frameworks that the cloud control belongs to.
  public var frameworkMajorRevisionIds: [Swift.Int64] = []

  /// The assessment details of the cloud control.
  public var assessmentDetails: AssessmentDetailsOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControlReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlReport().with { $0.manualCloudControlAssessmentDetails = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let manualCloudControlAssessmentDetails = CodingKeys(
      stringValue: "manualCloudControlAssessmentDetails")
    static let cloudControlAssessmentDetails = CodingKeys(
      stringValue: "cloudControlAssessmentDetails")
    static let cloudControl = CodingKeys(stringValue: "cloudControl")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let categories = CodingKeys(stringValue: "categories")
    static let similarControls = CodingKeys(stringValue: "similarControls")
    static let cloudControlType = CodingKeys(stringValue: "cloudControlType")
    static let findingCategory = CodingKeys(stringValue: "findingCategory")
    static let rules = CodingKeys(stringValue: "rules")
    static let findingSeverity = CodingKeys(stringValue: "findingSeverity")
    static let enforcementMode = CodingKeys(stringValue: "enforcementMode")
    static let cloudControlDeployment = CodingKeys(stringValue: "cloudControlDeployment")
    static let majorRevisionId = CodingKeys(stringValue: "majorRevisionId")
    static let minorRevisionId = CodingKeys(stringValue: "minorRevisionId")
    static let frameworkMajorRevisionIds = CodingKeys(stringValue: "frameworkMajorRevisionIds")

    static let _knownKeys: Set<Swift.String> = [
      "manualCloudControlAssessmentDetails",
      "cloudControlAssessmentDetails",
      "cloudControl",
      "displayName",
      "description",
      "categories",
      "similarControls",
      "cloudControlType",
      "findingCategory",
      "rules",
      "findingSeverity",
      "enforcementMode",
      "cloudControlDeployment",
      "majorRevisionId",
      "minorRevisionId",
      "frameworkMajorRevisionIds",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudControl) {
      self.cloudControl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .categories) {
      self.categories = value
    }
    if let value = try container.decodeIfPresent([SimilarControls].self, forKey: .similarControls) {
      self.similarControls = value
    }
    if let value = try container.decodeIfPresent(CloudControl.Type_.self, forKey: .cloudControlType)
    {
      self.cloudControlType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .findingCategory) {
      self.findingCategory = value
    }
    if let value = try container.decodeIfPresent([Rule].self, forKey: .rules) {
      self.rules = value
    }
    if let value = try container.decodeIfPresent(Severity.self, forKey: .findingSeverity) {
      self.findingSeverity = value
    }
    if let value = try container.decodeIfPresent(EnforcementMode.self, forKey: .enforcementMode) {
      self.enforcementMode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudControlDeployment)
    {
      self.cloudControlDeployment = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .majorRevisionId) {
      self.majorRevisionId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minorRevisionId) {
      self.minorRevisionId = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.Int64].self, forKey: .frameworkMajorRevisionIds)
    {
      self.frameworkMajorRevisionIds = value
    }

    var assessmentDetails: AssessmentDetailsOneOf? = nil
    let assessmentDetailsCheckAndSet = {
      if assessmentDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'assessmentDetails'"))
      }
      assessmentDetails = $0
    }
    if let manualCloudControlAssessmentDetails = try container.decodeIfPresent(
      ManualCloudControlAssessmentDetails.self, forKey: .manualCloudControlAssessmentDetails)
    {
      try assessmentDetailsCheckAndSet(
        .manualCloudControlAssessmentDetails(manualCloudControlAssessmentDetails))
    }
    if let cloudControlAssessmentDetails = try container.decodeIfPresent(
      CloudControlAssessmentDetails.self, forKey: .cloudControlAssessmentDetails)
    {
      try assessmentDetailsCheckAndSet(
        .cloudControlAssessmentDetails(cloudControlAssessmentDetails))
    }
    self.assessmentDetails = assessmentDetails
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cloudControl, forKey: .cloudControl)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.categories, forKey: .categories)
    try container.encode(self.similarControls, forKey: .similarControls)
    try container.encode(self.cloudControlType, forKey: .cloudControlType)
    try container.encode(self.findingCategory, forKey: .findingCategory)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.findingSeverity, forKey: .findingSeverity)
    try container.encode(self.enforcementMode, forKey: .enforcementMode)
    try container.encode(self.cloudControlDeployment, forKey: .cloudControlDeployment)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.minorRevisionId, forKey: .minorRevisionId)
    try container.encode(self.frameworkMajorRevisionIds, forKey: .frameworkMajorRevisionIds)

    if let choice = self.assessmentDetails {
      switch choice {
      case .manualCloudControlAssessmentDetails(let value):
        try container.encode(value, forKey: .manualCloudControlAssessmentDetails)
      case .cloudControlAssessmentDetails(let value):
        try container.encode(value, forKey: .cloudControlAssessmentDetails)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The assessment details of the cloud control.
  public enum AssessmentDetailsOneOf: Codable, Equatable, Sendable {
    /// The details of a manual cloud control assessment.
    indirect case manualCloudControlAssessmentDetails(ManualCloudControlAssessmentDetails)
    /// The details of a cloud control assessment.
    indirect case cloudControlAssessmentDetails(CloudControlAssessmentDetails)
  }

  /// The type URL for `CloudControlReport`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlReport"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlReport"
  }

  /// Initialize an instance of `CloudControlReport` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlReport"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CloudControlReport` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
