// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The category for the cloud control.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum CloudControlCategory: Codable, Equatable, Hashable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// The infrastructure security category.
  case ccCategoryInfrastructure
  /// The artificial intelligence category.
  case ccCategoryArtificialIntelligence
  /// The physical security category.
  case ccCategoryPhysicalSecurity
  /// The data security category.
  case ccCategoryDataSecurity
  /// The network security category.
  case ccCategoryNetworkSecurity
  /// The incident management category.
  case ccCategoryIncidentManagement
  /// The identity and access management category.
  case ccCategoryIdentityAndAccessManagement
  /// The encryption category.
  case ccCategoryEncryption
  /// The logs management and infrastructure category.
  case ccCategoryLogsManagementAndInfrastructure
  /// The HR, admin, and processes category.
  case ccCategoryHrAdminAndProcesses
  /// The third-party and sub-processor management category.
  case ccCategoryThirdPartyAndSubProcessorManagement
  /// The legal and disclosures category.
  case ccCategoryLegalAndDisclosures
  /// The vulnerability management category.
  case ccCategoryVulnerabilityManagement
  /// The privacy category.
  case ccCategoryPrivacy
  /// The business continuity and disaster recovery (BCDR) category.
  case ccCategoryBcdr
  /// The admin access category.
  case ccCategoryAdminAccess
  /// DRZ (Data Residency).
  case ccCategoryDataResidency
  /// RUR (Resource Usage Restriction).
  case ccCategoryResourceUsageRestriction
  /// SERVICE SPECIFIC
  case ccCategoryServiceSpecific
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .ccCategoryInfrastructure: return 1
    case .ccCategoryArtificialIntelligence: return 2
    case .ccCategoryPhysicalSecurity: return 3
    case .ccCategoryDataSecurity: return 4
    case .ccCategoryNetworkSecurity: return 5
    case .ccCategoryIncidentManagement: return 6
    case .ccCategoryIdentityAndAccessManagement: return 7
    case .ccCategoryEncryption: return 8
    case .ccCategoryLogsManagementAndInfrastructure: return 9
    case .ccCategoryHrAdminAndProcesses: return 10
    case .ccCategoryThirdPartyAndSubProcessorManagement: return 11
    case .ccCategoryLegalAndDisclosures: return 12
    case .ccCategoryVulnerabilityManagement: return 13
    case .ccCategoryPrivacy: return 14
    case .ccCategoryBcdr: return 15
    case .ccCategoryAdminAccess: return 16
    case .ccCategoryDataResidency: return 17
    case .ccCategoryResourceUsageRestriction: return 18
    case .ccCategoryServiceSpecific: return 19
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "CLOUD_CONTROL_CATEGORY_UNSPECIFIED"
    case .ccCategoryInfrastructure: return "CC_CATEGORY_INFRASTRUCTURE"
    case .ccCategoryArtificialIntelligence: return "CC_CATEGORY_ARTIFICIAL_INTELLIGENCE"
    case .ccCategoryPhysicalSecurity: return "CC_CATEGORY_PHYSICAL_SECURITY"
    case .ccCategoryDataSecurity: return "CC_CATEGORY_DATA_SECURITY"
    case .ccCategoryNetworkSecurity: return "CC_CATEGORY_NETWORK_SECURITY"
    case .ccCategoryIncidentManagement: return "CC_CATEGORY_INCIDENT_MANAGEMENT"
    case .ccCategoryIdentityAndAccessManagement: return "CC_CATEGORY_IDENTITY_AND_ACCESS_MANAGEMENT"
    case .ccCategoryEncryption: return "CC_CATEGORY_ENCRYPTION"
    case .ccCategoryLogsManagementAndInfrastructure:
      return "CC_CATEGORY_LOGS_MANAGEMENT_AND_INFRASTRUCTURE"
    case .ccCategoryHrAdminAndProcesses: return "CC_CATEGORY_HR_ADMIN_AND_PROCESSES"
    case .ccCategoryThirdPartyAndSubProcessorManagement:
      return "CC_CATEGORY_THIRD_PARTY_AND_SUB_PROCESSOR_MANAGEMENT"
    case .ccCategoryLegalAndDisclosures: return "CC_CATEGORY_LEGAL_AND_DISCLOSURES"
    case .ccCategoryVulnerabilityManagement: return "CC_CATEGORY_VULNERABILITY_MANAGEMENT"
    case .ccCategoryPrivacy: return "CC_CATEGORY_PRIVACY"
    case .ccCategoryBcdr: return "CC_CATEGORY_BCDR"
    case .ccCategoryAdminAccess: return "CC_CATEGORY_ADMIN_ACCESS"
    case .ccCategoryDataResidency: return "CC_CATEGORY_DATA_RESIDENCY"
    case .ccCategoryResourceUsageRestriction: return "CC_CATEGORY_RESOURCE_USAGE_RESTRICTION"
    case .ccCategoryServiceSpecific: return "CC_CATEGORY_SERVICE_SPECIFIC"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudControlCategory/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "CLOUD_CONTROL_CATEGORY_UNSPECIFIED": self = .unspecified
    case "CC_CATEGORY_INFRASTRUCTURE": self = .ccCategoryInfrastructure
    case "CC_CATEGORY_ARTIFICIAL_INTELLIGENCE": self = .ccCategoryArtificialIntelligence
    case "CC_CATEGORY_PHYSICAL_SECURITY": self = .ccCategoryPhysicalSecurity
    case "CC_CATEGORY_DATA_SECURITY": self = .ccCategoryDataSecurity
    case "CC_CATEGORY_NETWORK_SECURITY": self = .ccCategoryNetworkSecurity
    case "CC_CATEGORY_INCIDENT_MANAGEMENT": self = .ccCategoryIncidentManagement
    case "CC_CATEGORY_IDENTITY_AND_ACCESS_MANAGEMENT": self = .ccCategoryIdentityAndAccessManagement
    case "CC_CATEGORY_ENCRYPTION": self = .ccCategoryEncryption
    case "CC_CATEGORY_LOGS_MANAGEMENT_AND_INFRASTRUCTURE":
      self = .ccCategoryLogsManagementAndInfrastructure
    case "CC_CATEGORY_HR_ADMIN_AND_PROCESSES": self = .ccCategoryHrAdminAndProcesses
    case "CC_CATEGORY_THIRD_PARTY_AND_SUB_PROCESSOR_MANAGEMENT":
      self = .ccCategoryThirdPartyAndSubProcessorManagement
    case "CC_CATEGORY_LEGAL_AND_DISCLOSURES": self = .ccCategoryLegalAndDisclosures
    case "CC_CATEGORY_VULNERABILITY_MANAGEMENT": self = .ccCategoryVulnerabilityManagement
    case "CC_CATEGORY_PRIVACY": self = .ccCategoryPrivacy
    case "CC_CATEGORY_BCDR": self = .ccCategoryBcdr
    case "CC_CATEGORY_ADMIN_ACCESS": self = .ccCategoryAdminAccess
    case "CC_CATEGORY_DATA_RESIDENCY": self = .ccCategoryDataResidency
    case "CC_CATEGORY_RESOURCE_USAGE_RESTRICTION": self = .ccCategoryResourceUsageRestriction
    case "CC_CATEGORY_SERVICE_SPECIFIC": self = .ccCategoryServiceSpecific
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudControlCategory/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .ccCategoryInfrastructure
    case 2: self = .ccCategoryArtificialIntelligence
    case 3: self = .ccCategoryPhysicalSecurity
    case 4: self = .ccCategoryDataSecurity
    case 5: self = .ccCategoryNetworkSecurity
    case 6: self = .ccCategoryIncidentManagement
    case 7: self = .ccCategoryIdentityAndAccessManagement
    case 8: self = .ccCategoryEncryption
    case 9: self = .ccCategoryLogsManagementAndInfrastructure
    case 10: self = .ccCategoryHrAdminAndProcesses
    case 11: self = .ccCategoryThirdPartyAndSubProcessorManagement
    case 12: self = .ccCategoryLegalAndDisclosures
    case 13: self = .ccCategoryVulnerabilityManagement
    case 14: self = .ccCategoryPrivacy
    case 15: self = .ccCategoryBcdr
    case 16: self = .ccCategoryAdminAccess
    case 17: self = .ccCategoryDataResidency
    case 18: self = .ccCategoryResourceUsageRestriction
    case 19: self = .ccCategoryServiceSpecific
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("CLOUD_CONTROL_CATEGORY_UNSPECIFIED")
    case .ccCategoryInfrastructure: return try container.encode("CC_CATEGORY_INFRASTRUCTURE")
    case .ccCategoryArtificialIntelligence:
      return try container.encode("CC_CATEGORY_ARTIFICIAL_INTELLIGENCE")
    case .ccCategoryPhysicalSecurity: return try container.encode("CC_CATEGORY_PHYSICAL_SECURITY")
    case .ccCategoryDataSecurity: return try container.encode("CC_CATEGORY_DATA_SECURITY")
    case .ccCategoryNetworkSecurity: return try container.encode("CC_CATEGORY_NETWORK_SECURITY")
    case .ccCategoryIncidentManagement:
      return try container.encode("CC_CATEGORY_INCIDENT_MANAGEMENT")
    case .ccCategoryIdentityAndAccessManagement:
      return try container.encode("CC_CATEGORY_IDENTITY_AND_ACCESS_MANAGEMENT")
    case .ccCategoryEncryption: return try container.encode("CC_CATEGORY_ENCRYPTION")
    case .ccCategoryLogsManagementAndInfrastructure:
      return try container.encode("CC_CATEGORY_LOGS_MANAGEMENT_AND_INFRASTRUCTURE")
    case .ccCategoryHrAdminAndProcesses:
      return try container.encode("CC_CATEGORY_HR_ADMIN_AND_PROCESSES")
    case .ccCategoryThirdPartyAndSubProcessorManagement:
      return try container.encode("CC_CATEGORY_THIRD_PARTY_AND_SUB_PROCESSOR_MANAGEMENT")
    case .ccCategoryLegalAndDisclosures:
      return try container.encode("CC_CATEGORY_LEGAL_AND_DISCLOSURES")
    case .ccCategoryVulnerabilityManagement:
      return try container.encode("CC_CATEGORY_VULNERABILITY_MANAGEMENT")
    case .ccCategoryPrivacy: return try container.encode("CC_CATEGORY_PRIVACY")
    case .ccCategoryBcdr: return try container.encode("CC_CATEGORY_BCDR")
    case .ccCategoryAdminAccess: return try container.encode("CC_CATEGORY_ADMIN_ACCESS")
    case .ccCategoryDataResidency: return try container.encode("CC_CATEGORY_DATA_RESIDENCY")
    case .ccCategoryResourceUsageRestriction:
      return try container.encode("CC_CATEGORY_RESOURCE_USAGE_RESTRICTION")
    case .ccCategoryServiceSpecific: return try container.encode("CC_CATEGORY_SERVICE_SPECIFIC")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
