// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The details for a cloud control audit.
public struct CloudControlAuditDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the cloud control.
  public var cloudControl: Swift.String = Swift.String()

  /// Output only. The ID of the cloud control.
  public var cloudControlId: Swift.String = Swift.String()

  /// Output only. The description of the cloud control.
  public var cloudControlDescription: Swift.String = Swift.String()

  /// Output only. The overall status of the findings for the control.
  public var complianceState: ComplianceState = ComplianceState()

  /// Output only. The summary of the report.
  public var reportSummary: ReportSummary? = nil

  /// Output only. The findings for the control.
  public var findings: [FindingDetails] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControlAuditDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlAuditDetails().with { $0.cloudControl = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudControl = CodingKeys(stringValue: "cloudControl")
    static let cloudControlId = CodingKeys(stringValue: "cloudControlId")
    static let cloudControlDescription = CodingKeys(stringValue: "cloudControlDescription")
    static let complianceState = CodingKeys(stringValue: "complianceState")
    static let reportSummary = CodingKeys(stringValue: "reportSummary")
    static let findings = CodingKeys(stringValue: "findings")

    static let _knownKeys: Set<Swift.String> = [
      "cloudControl",
      "cloudControlId",
      "cloudControlDescription",
      "complianceState",
      "reportSummary",
      "findings",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudControl) {
      self.cloudControl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudControlId) {
      self.cloudControlId = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .cloudControlDescription)
    {
      self.cloudControlDescription = value
    }
    if let value = try container.decodeIfPresent(ComplianceState.self, forKey: .complianceState) {
      self.complianceState = value
    }
    self.reportSummary = try container.decodeIfPresent(ReportSummary.self, forKey: .reportSummary)
    if let value = try container.decodeIfPresent([FindingDetails].self, forKey: .findings) {
      self.findings = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cloudControl, forKey: .cloudControl)
    try container.encode(self.cloudControlId, forKey: .cloudControlId)
    try container.encode(self.cloudControlDescription, forKey: .cloudControlDescription)
    try container.encode(self.complianceState, forKey: .complianceState)
    try container.encodeIfPresent(self.reportSummary, forKey: .reportSummary)
    try container.encode(self.findings, forKey: .findings)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlAuditDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
