// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The details for a cloud control group.
public struct CloudControlGroupAuditDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The ID of the cloud control group.
  public var cloudControlGroupId: Swift.String = Swift.String()

  /// Output only. The display name of the cloud control group.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The description of the cloud control group.
  public var description: Swift.String = Swift.String()

  /// Output only. The responsibility type.
  public var responsibilityType: Swift.String = Swift.String()

  /// Output only. The description of Google's responsibility.
  public var googleResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. The implementation of Google's responsibility.
  public var googleResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. The description of your responsibility.
  public var customerResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. The implementation of your responsibility.
  public var customerResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. The compliance state of the control group.
  public var complianceState: ComplianceState = ComplianceState()

  /// Output only. The ID of the regulatory control.
  public var controlId: Swift.String = Swift.String()

  /// Output only. The control family.
  public var controlFamily: ControlFamily? = nil

  /// Output only. The details for the cloud controls within this group.
  public var cloudControlDetails: [CloudControlAuditDetails] = []

  /// Output only. The summary of the report.
  public var reportSummary: ReportSummary? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControlGroupAuditDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlGroupAuditDetails().with { $0.cloudControlGroupId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let cloudControlGroupId = CodingKeys(stringValue: "cloudControlGroupId")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let responsibilityType = CodingKeys(stringValue: "responsibilityType")
    static let googleResponsibilityDescription = CodingKeys(
      stringValue: "googleResponsibilityDescription")
    static let googleResponsibilityImplementation = CodingKeys(
      stringValue: "googleResponsibilityImplementation")
    static let customerResponsibilityDescription = CodingKeys(
      stringValue: "customerResponsibilityDescription")
    static let customerResponsibilityImplementation = CodingKeys(
      stringValue: "customerResponsibilityImplementation")
    static let complianceState = CodingKeys(stringValue: "complianceState")
    static let controlId = CodingKeys(stringValue: "controlId")
    static let controlFamily = CodingKeys(stringValue: "controlFamily")
    static let cloudControlDetails = CodingKeys(stringValue: "cloudControlDetails")
    static let reportSummary = CodingKeys(stringValue: "reportSummary")

    static let _knownKeys: Set<Swift.String> = [
      "cloudControlGroupId",
      "displayName",
      "description",
      "responsibilityType",
      "googleResponsibilityDescription",
      "googleResponsibilityImplementation",
      "customerResponsibilityDescription",
      "customerResponsibilityImplementation",
      "complianceState",
      "controlId",
      "controlFamily",
      "cloudControlDetails",
      "reportSummary",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cloudControlGroupId) {
      self.cloudControlGroupId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .responsibilityType) {
      self.responsibilityType = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .googleResponsibilityDescription)
    {
      self.googleResponsibilityDescription = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .googleResponsibilityImplementation)
    {
      self.googleResponsibilityImplementation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .customerResponsibilityDescription)
    {
      self.customerResponsibilityDescription = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .customerResponsibilityImplementation)
    {
      self.customerResponsibilityImplementation = value
    }
    if let value = try container.decodeIfPresent(ComplianceState.self, forKey: .complianceState) {
      self.complianceState = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .controlId) {
      self.controlId = value
    }
    self.controlFamily = try container.decodeIfPresent(ControlFamily.self, forKey: .controlFamily)
    if let value = try container.decodeIfPresent(
      [CloudControlAuditDetails].self, forKey: .cloudControlDetails)
    {
      self.cloudControlDetails = value
    }
    self.reportSummary = try container.decodeIfPresent(ReportSummary.self, forKey: .reportSummary)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.cloudControlGroupId, forKey: .cloudControlGroupId)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.responsibilityType, forKey: .responsibilityType)
    try container.encode(
      self.googleResponsibilityDescription, forKey: .googleResponsibilityDescription)
    try container.encode(
      self.googleResponsibilityImplementation, forKey: .googleResponsibilityImplementation)
    try container.encode(
      self.customerResponsibilityDescription, forKey: .customerResponsibilityDescription)
    try container.encode(
      self.customerResponsibilityImplementation, forKey: .customerResponsibilityImplementation)
    try container.encode(self.complianceState, forKey: .complianceState)
    try container.encode(self.controlId, forKey: .controlId)
    try container.encodeIfPresent(self.controlFamily, forKey: .controlFamily)
    try container.encode(self.cloudControlDetails, forKey: .cloudControlDetails)
    try container.encodeIfPresent(self.reportSummary, forKey: .reportSummary)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlGroupAuditDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
