// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A cloud control deployment represents the deployment of a particular cloud
/// control on a target resource. Supported target resources are
/// `organizations/{organizationID}`, `folders/{folderID}`, and
/// `projects/{projectID}`.
public struct CloudControlDeployment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name for the cloud control deployment, in the format
  /// `organizations/{organization}/locations/{location}/cloudControlDeployments/{cloud_control_deployment}`
  /// or
  /// `projects/{project}/locations/{location}/cloudControlDeployments/{cloud_control_deployment}`.
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Required. The details of the target resource that the cloud control is
  /// deployed You can use an existing target resource or create a new target.
  public var targetResourceConfig: TargetResourceConfig? = nil

  /// Output only. The resource that the cloud control is deployed on, in one of
  /// the following formats:
  ///
  /// - `organizations/{organizationID}`
  /// - `folders/{folderID}`
  /// - `projects/{projectID}`
  public var targetResource: Swift.String = Swift.String()

  /// Required. The deployment mode and parameters for the cloud control.
  public var cloudControlMetadata: CloudControlMetadata? = nil

  /// Optional. A friendly description for the cloud control deployment.
  public var description: Swift.String = Swift.String()

  /// Output only. The state of the cloud control deployment.
  public var deploymentState: DeploymentState = DeploymentState()

  /// Output only. The time when the resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the resource was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. To prevent concurrent updates from overwriting each other,
  /// provide the `etag` when you update a cloud control deployment. You can also
  /// provide the `etag` when you delete a cloud control deployment to help
  /// ensure that you're deleting the intended version of the
  /// deployment.
  public var etag: Swift.String = Swift.String()

  /// Output only. The cloud control after the given parameters are substituted.
  public var parameterSubstitutedCloudControl: CloudControl? = nil

  /// Output only. The references to the framework deployments that this cloud
  /// control deployment is part of. A cloud control deployment can be part of
  /// multiple framework deployments.
  public var frameworkDeploymentReferences: [FrameworkDeploymentReference] = []

  /// Output only. The display name of the target resource.
  public var targetResourceDisplayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControlDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlDeployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let targetResourceConfig = CodingKeys(stringValue: "targetResourceConfig")
    static let targetResource = CodingKeys(stringValue: "targetResource")
    static let cloudControlMetadata = CodingKeys(stringValue: "cloudControlMetadata")
    static let description = CodingKeys(stringValue: "description")
    static let deploymentState = CodingKeys(stringValue: "deploymentState")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let parameterSubstitutedCloudControl = CodingKeys(
      stringValue: "parameterSubstitutedCloudControl")
    static let frameworkDeploymentReferences = CodingKeys(
      stringValue: "frameworkDeploymentReferences")
    static let targetResourceDisplayName = CodingKeys(stringValue: "targetResourceDisplayName")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "targetResourceConfig",
      "targetResource",
      "cloudControlMetadata",
      "description",
      "deploymentState",
      "createTime",
      "updateTime",
      "etag",
      "parameterSubstitutedCloudControl",
      "frameworkDeploymentReferences",
      "targetResourceDisplayName",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.targetResourceConfig = try container.decodeIfPresent(
      TargetResourceConfig.self, forKey: .targetResourceConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetResource) {
      self.targetResource = value
    }
    self.cloudControlMetadata = try container.decodeIfPresent(
      CloudControlMetadata.self, forKey: .cloudControlMetadata)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .deploymentState) {
      self.deploymentState = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    self.parameterSubstitutedCloudControl = try container.decodeIfPresent(
      CloudControl.self, forKey: .parameterSubstitutedCloudControl)
    if let value = try container.decodeIfPresent(
      [FrameworkDeploymentReference].self, forKey: .frameworkDeploymentReferences)
    {
      self.frameworkDeploymentReferences = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .targetResourceDisplayName)
    {
      self.targetResourceDisplayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.targetResourceConfig, forKey: .targetResourceConfig)
    try container.encode(self.targetResource, forKey: .targetResource)
    try container.encodeIfPresent(self.cloudControlMetadata, forKey: .cloudControlMetadata)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.deploymentState, forKey: .deploymentState)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encodeIfPresent(
      self.parameterSubstitutedCloudControl, forKey: .parameterSubstitutedCloudControl)
    try container.encode(self.frameworkDeploymentReferences, forKey: .frameworkDeploymentReferences)
    try container.encode(self.targetResourceDisplayName, forKey: .targetResourceDisplayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlDeployment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
