// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A cloud control is a set of rules and associated metadata that you can
/// use to define your organization's security or compliance intent.
public struct CloudControl: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. The name of the cloud control, in either of the
  /// formats:
  /// `organizations/{organization}/locations/{location}/cloudControls/{cloud_control}`
  /// or
  /// `projects/{project}/locations/{location}/cloudControls/{cloud_control}`.
  ///
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Output only. The major version of the cloud control, which is incremented
  /// in ascending order.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// Optional. A description of the cloud control. The maximum length is 2000
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Optional. The friendly name of the cloud control. The maximum length is 200
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The supported enforcement modes for the cloud control.
  public var supportedEnforcementModes: [EnforcementMode] = []

  /// Optional. The parameter specifications for the cloud control.
  public var parameterSpec: [ParameterSpec] = []

  /// Optional. The rules that you can enforce to meet your security or
  /// compliance intent.
  public var rules: [Rule] = []

  /// Optional. The severity of the findings that are generated by the cloud
  /// control.
  public var severity: Severity = Severity()

  /// Optional. The finding category for the cloud control findings. The maximum
  /// length is 255 characters.
  public var findingCategory: Swift.String = Swift.String()

  /// Optional. The supported cloud providers.
  public var supportedCloudProviders: [CloudProvider] = []

  /// Output only. The frameworks that include this cloud control.
  public var relatedFrameworks: [Swift.String] = []

  /// Optional. The remediation steps for the cloud control findings. The
  /// maximum length is 400 characters.
  public var remediationSteps: Swift.String = Swift.String()

  /// Optional. The categories for the cloud control.
  public var categories: [CloudControlCategory] = []

  /// Output only. The time that the cloud control was last updated.
  /// `create_time` is used because a new cloud control is created
  /// whenever an existing cloud control is updated.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. The target resource types that are supported by the cloud
  /// control.
  public var supportedTargetResourceTypes: [TargetResourceType] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControl`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControl().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let majorRevisionId = CodingKeys(stringValue: "majorRevisionId")
    static let description = CodingKeys(stringValue: "description")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let supportedEnforcementModes = CodingKeys(stringValue: "supportedEnforcementModes")
    static let parameterSpec = CodingKeys(stringValue: "parameterSpec")
    static let rules = CodingKeys(stringValue: "rules")
    static let severity = CodingKeys(stringValue: "severity")
    static let findingCategory = CodingKeys(stringValue: "findingCategory")
    static let supportedCloudProviders = CodingKeys(stringValue: "supportedCloudProviders")
    static let relatedFrameworks = CodingKeys(stringValue: "relatedFrameworks")
    static let remediationSteps = CodingKeys(stringValue: "remediationSteps")
    static let categories = CodingKeys(stringValue: "categories")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let supportedTargetResourceTypes = CodingKeys(
      stringValue: "supportedTargetResourceTypes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "majorRevisionId",
      "description",
      "displayName",
      "supportedEnforcementModes",
      "parameterSpec",
      "rules",
      "severity",
      "findingCategory",
      "supportedCloudProviders",
      "relatedFrameworks",
      "remediationSteps",
      "categories",
      "createTime",
      "supportedTargetResourceTypes",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .majorRevisionId) {
      self.majorRevisionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      [EnforcementMode].self, forKey: .supportedEnforcementModes)
    {
      self.supportedEnforcementModes = value
    }
    if let value = try container.decodeIfPresent([ParameterSpec].self, forKey: .parameterSpec) {
      self.parameterSpec = value
    }
    if let value = try container.decodeIfPresent([Rule].self, forKey: .rules) {
      self.rules = value
    }
    if let value = try container.decodeIfPresent(Severity.self, forKey: .severity) {
      self.severity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .findingCategory) {
      self.findingCategory = value
    }
    if let value = try container.decodeIfPresent(
      [CloudProvider].self, forKey: .supportedCloudProviders)
    {
      self.supportedCloudProviders = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .relatedFrameworks) {
      self.relatedFrameworks = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .remediationSteps) {
      self.remediationSteps = value
    }
    if let value = try container.decodeIfPresent([CloudControlCategory].self, forKey: .categories) {
      self.categories = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(
      [TargetResourceType].self, forKey: .supportedTargetResourceTypes)
    {
      self.supportedTargetResourceTypes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.supportedEnforcementModes, forKey: .supportedEnforcementModes)
    try container.encode(self.parameterSpec, forKey: .parameterSpec)
    try container.encode(self.rules, forKey: .rules)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.findingCategory, forKey: .findingCategory)
    try container.encode(self.supportedCloudProviders, forKey: .supportedCloudProviders)
    try container.encode(self.relatedFrameworks, forKey: .relatedFrameworks)
    try container.encode(self.remediationSteps, forKey: .remediationSteps)
    try container.encode(self.categories, forKey: .categories)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.supportedTargetResourceTypes, forKey: .supportedTargetResourceTypes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of cloud control.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// A cloud control that's created and managed by you.
    case custom
    /// A cloud control that's provided and managed by Google.
    case builtIn
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .custom: return 1
      case .builtIn: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .custom: return "CUSTOM"
      case .builtIn: return "BUILT_IN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "CUSTOM": self = .custom
      case "BUILT_IN": self = .builtIn
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .custom
      case 2: self = .builtIn
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .custom: return try container.encode("CUSTOM")
      case .builtIn: return try container.encode("BUILT_IN")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `CloudControl`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControl"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControl"
  }

  /// Initialize an instance of `CloudControl` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControl"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `CloudControl` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
