// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The details of a cloud control.
public struct CloudControlDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the cloud control, in one of the following formats:
  /// `organizations/{organization}/locations/{location}/cloudControls/{cloud_control}`
  /// or
  /// `projects/{project}/locations/{location}/cloudControls/{cloud_control}`.
  ///
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Required. The major version of the cloud control.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// Optional. Parameters are key-value pairs that let you provide your custom
  /// location requirements, environment requirements, or other settings that are
  /// relevant to the cloud control. An example parameter is
  /// `{"name": "location","value": "us-west-1"}`.
  public var parameters: [Parameter] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CloudControlDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudControlDetails().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let majorRevisionId = CodingKeys(stringValue: "majorRevisionId")
    static let parameters = CodingKeys(stringValue: "parameters")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "majorRevisionId",
      "parameters",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .majorRevisionId) {
      self.majorRevisionId = value
    }
    if let value = try container.decodeIfPresent([Parameter].self, forKey: .parameters) {
      self.parameters = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.parameters, forKey: .parameters)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CloudControlDetails"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
