// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing CmEnrollment related RPCs for
/// complianceManager.
///
/// @Snippet(path: "CmEnrollmentServiceQuickstart")
public final class CmEnrollmentServiceClient: Clients.CmEnrollmentServiceProtocol, Sendable {
  let inner: any Clients.CmEnrollmentServiceStub

  /// Creates a new `CmEnrollmentServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.CmEnrollmentServiceStub = try Clients.CmEnrollmentServiceTransport(
      options)
    inner = Clients.CmEnrollmentServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.CmEnrollmentServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Updates the Compliance Manager enrollment for a resource to facilitate
  /// an audit.
  /// Use this method to enroll a resource in Compliance Manager or to
  /// create or update feature-specific configurations.
  ///
  /// @Snippet(path: "CmEnrollmentService_UpdateCmEnrollment")
  public func updateCmEnrollment(
    request: UpdateCmEnrollmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CmEnrollment {
    try await self.inner.updateCmEnrollment(request: request, options: options)
  }

  /// Calculates the effective Compliance Manager enrollment for a resource.
  /// An effective enrollment is either a direct enrollment of a
  /// resource (if it exists), or an enrollment of the closest parent of a
  /// resource that's enrolled in Compliance Manager.
  ///
  /// @Snippet(path: "CmEnrollmentService_CalculateEffectiveCmEnrollment")
  public func calculateEffectiveCmEnrollment(
    request: CalculateEffectiveCmEnrollmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CalculateEffectiveCmEnrollmentResponse {
    try await self.inner.calculateEffectiveCmEnrollment(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "CmEnrollmentService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "CmEnrollmentService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CmEnrollmentService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CmEnrollmentService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CmEnrollmentService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CmEnrollmentService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `CmEnrollmentServiceClient`.
  ///
  /// To mock `CmEnrollmentServiceClient` change your functions to receive
  /// `some CmEnrollmentServiceProtocol` or `any CmEnrollmentServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol CmEnrollmentServiceProtocol: Sendable {
    /// See `CmEnrollmentServiceClient.updateCmEnrollment`.
    func updateCmEnrollment(
      request: UpdateCmEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CmEnrollment

    /// See `CmEnrollmentServiceClient.calculateEffectiveCmEnrollment`.
    func calculateEffectiveCmEnrollment(
      request: CalculateEffectiveCmEnrollmentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CalculateEffectiveCmEnrollmentResponse

    /// See `CmEnrollmentServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `CmEnrollmentServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `CmEnrollmentServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `CmEnrollmentServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `CmEnrollmentServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.CmEnrollmentServiceProtocol {
  public func updateCmEnrollment(request: UpdateCmEnrollmentRequest) async throws
    -> GoogleCloudSecurityComplianceV1.CmEnrollment
  {
    try await self.updateCmEnrollment(request: request, options: .init())
  }

  public func updateCmEnrollment(
    request: UpdateCmEnrollmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CmEnrollment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateCmEnrollment(
    cmEnrollment: CmEnrollment?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> GoogleCloudSecurityComplianceV1.CmEnrollment {
    let request = UpdateCmEnrollmentRequest().with {
      $0.cmEnrollment = cmEnrollment
      $0.updateMask = updateMask
    }
    return try await self.updateCmEnrollment(request: request)
  }

  public func calculateEffectiveCmEnrollment(request: CalculateEffectiveCmEnrollmentRequest)
    async throws -> GoogleCloudSecurityComplianceV1.CalculateEffectiveCmEnrollmentResponse
  {
    try await self.calculateEffectiveCmEnrollment(request: request, options: .init())
  }

  public func calculateEffectiveCmEnrollment(
    request: CalculateEffectiveCmEnrollmentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CalculateEffectiveCmEnrollmentResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func calculateEffectiveCmEnrollment(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.CalculateEffectiveCmEnrollmentResponse {
    let request = CalculateEffectiveCmEnrollmentRequest().with {
      $0.name = name
    }
    return try await self.calculateEffectiveCmEnrollment(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "CmEnrollmentService_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "CmEnrollmentService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
