// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The settings for Compliance Manager at a specific resource scope.=
public struct CmEnrollment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the Compliance Manager enrollment.
  ///
  /// Supported formats are the following:
  ///
  /// * `organizations/{organization_id}/locations/{location}/cmEnrollment`
  /// * `folders/{folder_id}/locations/{location}/cmEnrollment`
  /// * `projects/{project_id}/locations/{location}/cmEnrollment`
  public var name: Swift.String = Swift.String()

  /// Optional. Whether the resource is enrolled in Compliance Manager.
  /// This setting is inherited by all descendants.
  public var enrolled: Swift.Bool = Swift.Bool()

  /// Optional. The audit configuration for Compliance Manager.
  /// If set at a scope, this configuration overrides any inherited audit
  /// configuration.
  public var auditConfig: AuditConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CmEnrollment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CmEnrollment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let enrolled = CodingKeys(stringValue: "enrolled")
    static let auditConfig = CodingKeys(stringValue: "auditConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "enrolled",
      "auditConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enrolled) {
      self.enrolled = value
    }
    self.auditConfig = try container.decodeIfPresent(AuditConfig.self, forKey: .auditConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.enrolled, forKey: .enrolled)
    try container.encodeIfPresent(self.auditConfig, forKey: .auditConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.CmEnrollment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
