// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The regulatory control.
public struct Control: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of a regulatory control, in one of the following
  /// formats:
  /// - `organizations/{organization}/locations/{location}/controls/{control}`
  /// - `projects/{project}/locations/{location}/controls/{control}`.
  ///
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Output only. The friendly name for the regulatory control.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The description of the regulatory control.
  public var description: Swift.String = Swift.String()

  /// Output only. The regulatory group that the control belongs to.
  public var family: Control.Family = Control.Family()

  /// Output only. The regulatory family that the control belongs to.
  public var controlFamily: ControlFamily? = nil

  /// Output only. The entity that's responsible for the control, whether Google,
  /// you as the customer, or both.
  public var responsibilityType: RegulatoryControlResponsibilityType =
    RegulatoryControlResponsibilityType()

  /// Output only. A description of Google's responsibility for the regulatory
  /// control.
  public var googleResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. A description of Google's responsibility for implementing the
  /// regulatory control.
  public var googleResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. A description of your responsibility for the regulatory
  /// control.
  public var customerResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. A description of the your responsibility for implementing the
  /// regulatory control.
  public var customerResponsibilityImplementation: Swift.String = Swift.String()

  /// Output only. A description of the responsibility that's shared between
  /// Google and you in implementing this control.
  public var sharedResponsibilityDescription: Swift.String = Swift.String()

  /// Output only. A link to the documentation that's related to this control.
  public var additionalContentUri: Swift.String = Swift.String()

  /// Output only. The frameworks that include this control.
  public var relatedFrameworks: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Control`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Control().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let family = CodingKeys(stringValue: "family")
    static let controlFamily = CodingKeys(stringValue: "controlFamily")
    static let responsibilityType = CodingKeys(stringValue: "responsibilityType")
    static let googleResponsibilityDescription = CodingKeys(
      stringValue: "googleResponsibilityDescription")
    static let googleResponsibilityImplementation = CodingKeys(
      stringValue: "googleResponsibilityImplementation")
    static let customerResponsibilityDescription = CodingKeys(
      stringValue: "customerResponsibilityDescription")
    static let customerResponsibilityImplementation = CodingKeys(
      stringValue: "customerResponsibilityImplementation")
    static let sharedResponsibilityDescription = CodingKeys(
      stringValue: "sharedResponsibilityDescription")
    static let additionalContentUri = CodingKeys(stringValue: "additionalContentUri")
    static let relatedFrameworks = CodingKeys(stringValue: "relatedFrameworks")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "family",
      "controlFamily",
      "responsibilityType",
      "googleResponsibilityDescription",
      "googleResponsibilityImplementation",
      "customerResponsibilityDescription",
      "customerResponsibilityImplementation",
      "sharedResponsibilityDescription",
      "additionalContentUri",
      "relatedFrameworks",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Control.Family.self, forKey: .family) {
      self.family = value
    }
    self.controlFamily = try container.decodeIfPresent(ControlFamily.self, forKey: .controlFamily)
    if let value = try container.decodeIfPresent(
      RegulatoryControlResponsibilityType.self, forKey: .responsibilityType)
    {
      self.responsibilityType = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .googleResponsibilityDescription)
    {
      self.googleResponsibilityDescription = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .googleResponsibilityImplementation)
    {
      self.googleResponsibilityImplementation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .customerResponsibilityDescription)
    {
      self.customerResponsibilityDescription = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .customerResponsibilityImplementation)
    {
      self.customerResponsibilityImplementation = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .sharedResponsibilityDescription)
    {
      self.sharedResponsibilityDescription = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .additionalContentUri) {
      self.additionalContentUri = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .relatedFrameworks) {
      self.relatedFrameworks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.family, forKey: .family)
    try container.encodeIfPresent(self.controlFamily, forKey: .controlFamily)
    try container.encode(self.responsibilityType, forKey: .responsibilityType)
    try container.encode(
      self.googleResponsibilityDescription, forKey: .googleResponsibilityDescription)
    try container.encode(
      self.googleResponsibilityImplementation, forKey: .googleResponsibilityImplementation)
    try container.encode(
      self.customerResponsibilityDescription, forKey: .customerResponsibilityDescription)
    try container.encode(
      self.customerResponsibilityImplementation, forKey: .customerResponsibilityImplementation)
    try container.encode(
      self.sharedResponsibilityDescription, forKey: .sharedResponsibilityDescription)
    try container.encode(self.additionalContentUri, forKey: .additionalContentUri)
    try container.encode(self.relatedFrameworks, forKey: .relatedFrameworks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The regulatory control family.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Family: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Access control
    case ac
    /// Awareness and araining
    case at
    /// Audit and accountability
    case au
    /// Certification, accreditation, and security assessments
    case ca
    /// Configuration management
    case cm
    /// Contingency planning
    case cp
    /// Identification and authentication
    case ia
    /// Incident response
    case ir
    /// Maintenance
    case ma
    /// Media protection
    case mp
    /// Physical and environmental protection
    case pe
    /// Security planning
    case pl
    /// Personnel aecurity
    case ps
    /// Risk assessment
    case ra
    /// System services and acquisition
    case sa
    /// System and communications protection
    case sc
    /// System and information integrity
    case si
    /// Supply chain risk management
    case sr
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ac: return 1
      case .at: return 2
      case .au: return 3
      case .ca: return 4
      case .cm: return 5
      case .cp: return 6
      case .ia: return 7
      case .ir: return 8
      case .ma: return 9
      case .mp: return 10
      case .pe: return 11
      case .pl: return 12
      case .ps: return 13
      case .ra: return 14
      case .sa: return 15
      case .sc: return 16
      case .si: return 17
      case .sr: return 18
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FAMILY_UNSPECIFIED"
      case .ac: return "AC"
      case .at: return "AT"
      case .au: return "AU"
      case .ca: return "CA"
      case .cm: return "CM"
      case .cp: return "CP"
      case .ia: return "IA"
      case .ir: return "IR"
      case .ma: return "MA"
      case .mp: return "MP"
      case .pe: return "PE"
      case .pl: return "PL"
      case .ps: return "PS"
      case .ra: return "RA"
      case .sa: return "SA"
      case .sc: return "SC"
      case .si: return "SI"
      case .sr: return "SR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Family/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FAMILY_UNSPECIFIED": self = .unspecified
      case "AC": self = .ac
      case "AT": self = .at
      case "AU": self = .au
      case "CA": self = .ca
      case "CM": self = .cm
      case "CP": self = .cp
      case "IA": self = .ia
      case "IR": self = .ir
      case "MA": self = .ma
      case "MP": self = .mp
      case "PE": self = .pe
      case "PL": self = .pl
      case "PS": self = .ps
      case "RA": self = .ra
      case "SA": self = .sa
      case "SC": self = .sc
      case "SI": self = .si
      case "SR": self = .sr
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Family/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ac
      case 2: self = .at
      case 3: self = .au
      case 4: self = .ca
      case 5: self = .cm
      case 6: self = .cp
      case 7: self = .ia
      case 8: self = .ir
      case 9: self = .ma
      case 10: self = .mp
      case 11: self = .pe
      case 12: self = .pl
      case 13: self = .ps
      case 14: self = .ra
      case 15: self = .sa
      case 16: self = .sc
      case 17: self = .si
      case 18: self = .sr
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FAMILY_UNSPECIFIED")
      case .ac: return try container.encode("AC")
      case .at: return try container.encode("AT")
      case .au: return try container.encode("AU")
      case .ca: return try container.encode("CA")
      case .cm: return try container.encode("CM")
      case .cp: return try container.encode("CP")
      case .ia: return try container.encode("IA")
      case .ir: return try container.encode("IR")
      case .ma: return try container.encode("MA")
      case .mp: return try container.encode("MP")
      case .pe: return try container.encode("PE")
      case .pl: return try container.encode("PL")
      case .ps: return try container.encode("PS")
      case .ra: return try container.encode("RA")
      case .sa: return try container.encode("SA")
      case .sc: return try container.encode("SC")
      case .si: return try container.encode("SI")
      case .sr: return try container.encode("SR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Control"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
