// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The details for control compliance.
public struct ControlComplianceSummary: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the control.
  public var control: Swift.String = Swift.String()

  /// The display name of the control.
  public var displayName: Swift.String = Swift.String()

  /// The description of the control.
  public var description: Swift.String = Swift.String()

  /// Output only. The overall evaluation status of the control.
  public var overallEvaluationState: EvaluationState = EvaluationState()

  /// The total number of findings for the control.
  public var totalFindingsCount: Swift.Int32 = Swift.Int32()

  /// The list of compliance frameworks that the control belongs to.
  public var complianceFrameworks: [Swift.String] = []

  /// The list of similar controls.
  public var similarControls: [SimilarControls] = []

  /// The list of cloud control reports.
  public var cloudControlReports: [CloudControlReport] = []

  /// The responsibility type for the control.
  public var controlResponsibilityType: RegulatoryControlResponsibilityType =
    RegulatoryControlResponsibilityType()

  /// Whether the control is a fake control. Fake controls are created
  /// and mapped to cloud controls that don't belong to a control group.
  public var isFakeControl: Swift.Bool = Swift.Bool()

  /// Identifier. The name of the control compliance summary.
  public var name: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ControlComplianceSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ControlComplianceSummary().with { $0.control = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let control = CodingKeys(stringValue: "control")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let overallEvaluationState = CodingKeys(stringValue: "overallEvaluationState")
    static let totalFindingsCount = CodingKeys(stringValue: "totalFindingsCount")
    static let complianceFrameworks = CodingKeys(stringValue: "complianceFrameworks")
    static let similarControls = CodingKeys(stringValue: "similarControls")
    static let cloudControlReports = CodingKeys(stringValue: "cloudControlReports")
    static let controlResponsibilityType = CodingKeys(stringValue: "controlResponsibilityType")
    static let isFakeControl = CodingKeys(stringValue: "isFakeControl")
    static let name = CodingKeys(stringValue: "name")

    static let _knownKeys: Set<Swift.String> = [
      "control",
      "displayName",
      "description",
      "overallEvaluationState",
      "totalFindingsCount",
      "complianceFrameworks",
      "similarControls",
      "cloudControlReports",
      "controlResponsibilityType",
      "isFakeControl",
      "name",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .control) {
      self.control = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      EvaluationState.self, forKey: .overallEvaluationState)
    {
      self.overallEvaluationState = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalFindingsCount) {
      self.totalFindingsCount = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .complianceFrameworks)
    {
      self.complianceFrameworks = value
    }
    if let value = try container.decodeIfPresent([SimilarControls].self, forKey: .similarControls) {
      self.similarControls = value
    }
    if let value = try container.decodeIfPresent(
      [CloudControlReport].self, forKey: .cloudControlReports)
    {
      self.cloudControlReports = value
    }
    if let value = try container.decodeIfPresent(
      RegulatoryControlResponsibilityType.self, forKey: .controlResponsibilityType)
    {
      self.controlResponsibilityType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isFakeControl) {
      self.isFakeControl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.control, forKey: .control)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.overallEvaluationState, forKey: .overallEvaluationState)
    try container.encode(self.totalFindingsCount, forKey: .totalFindingsCount)
    try container.encode(self.complianceFrameworks, forKey: .complianceFrameworks)
    try container.encode(self.similarControls, forKey: .similarControls)
    try container.encode(self.cloudControlReports, forKey: .cloudControlReports)
    try container.encode(self.controlResponsibilityType, forKey: .controlResponsibilityType)
    try container.encode(self.isFakeControl, forKey: .isFakeControl)
    try container.encode(self.name, forKey: .name)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ControlComplianceSummary`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ControlComplianceSummary"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ControlComplianceSummary"
  }

  /// Initialize an instance of `ControlComplianceSummary` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ControlComplianceSummary"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ControlComplianceSummary` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
