// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Deployment service allows users to manage deployments of Frameworks and
/// Cloud Controls on a target resource.
///
/// @Snippet(path: "DeploymentQuickstart")
public final class DeploymentClient: Clients.DeploymentProtocol, Sendable {
  let inner: any Clients.DeploymentStub
  let pollingErrorPolicy: any GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: any GoogleGax.PollingBackoffPolicy

  /// Creates a new `DeploymentClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DeploymentStub = try Clients.DeploymentTransport(options)
    inner = Clients.DeploymentRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DeploymentLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a framework deployment in a given parent resource. A
  /// framework deployment lets you assign a particular framework version to an
  /// organization, folder, or project so that you can control and monitor
  /// those resources using the framework's cloud controls.
  ///
  /// @Snippet(path: "Deployment_CreateFrameworkDeployment")
  public func createFrameworkDeployment(
    request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createFrameworkDeployment(request: request, options: options)
  }

  /// Creates a framework deployment in a given parent resource. A
  /// framework deployment lets you assign a particular framework version to an
  /// organization, folder, or project so that you can control and monitor
  /// those resources using the framework's cloud controls.
  ///
  /// @Snippet(path: "Deployment_CreateFrameworkDeployment")
  public func createFrameworkDeploymentPollingUntilDone(
    request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> FrameworkDeployment {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<FrameworkDeployment>.State in
      return try op._extractStatus(FrameworkDeployment.self)
    }
    let rawOp = try await self.createFrameworkDeployment(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<FrameworkDeployment>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a framework deployment.
  ///
  /// @Snippet(path: "Deployment_DeleteFrameworkDeployment")
  public func deleteFrameworkDeployment(
    request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteFrameworkDeployment(request: request, options: options)
  }

  /// Deletes a framework deployment.
  ///
  /// @Snippet(path: "Deployment_DeleteFrameworkDeployment")
  public func deleteFrameworkDeploymentPollingUntilDone(
    request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteFrameworkDeployment(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Gets details about a framework deployment.
  ///
  /// @Snippet(path: "Deployment_GetFrameworkDeployment")
  public func getFrameworkDeployment(
    request: GetFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkDeployment {
    try await self.inner.getFrameworkDeployment(request: request, options: options)
  }

  /// Lists the framework deployments in a given parent resource.
  ///
  /// @Snippet(path: "Deployment_ListFrameworkDeployments")
  public func listFrameworkDeployments(
    request: ListFrameworkDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkDeploymentsResponse {
    try await self.inner.listFrameworkDeployments(request: request, options: options)
  }

  /// Gets details about a cloud control deployment.
  ///
  /// @Snippet(path: "Deployment_GetCloudControlDeployment")
  public func getCloudControlDeployment(
    request: GetCloudControlDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControlDeployment {
    try await self.inner.getCloudControlDeployment(request: request, options: options)
  }

  /// Lists the cloud conrol deployments in a given parent resource.
  ///
  /// @Snippet(path: "Deployment_ListCloudControlDeployments")
  public func listCloudControlDeployments(
    request: ListCloudControlDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlDeploymentsResponse {
    try await self.inner.listCloudControlDeployments(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Deployment_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Deployment_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Deployment_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Deployment_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Deployment_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Deployment_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DeploymentClient`.
  ///
  /// To mock `DeploymentClient` change your functions to receive
  /// `some DeploymentProtocol` or `any DeploymentProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DeploymentProtocol: Sendable {
    /// See `DeploymentClient.createFrameworkDeployment`.
    func createFrameworkDeployment(
      request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeploymentClient.createFrameworkDeployment`.
    func createFrameworkDeploymentPollingUntilDone(
      request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> FrameworkDeployment

    /// See `DeploymentClient.deleteFrameworkDeployment`.
    func deleteFrameworkDeployment(
      request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DeploymentClient.deleteFrameworkDeployment`.
    func deleteFrameworkDeploymentPollingUntilDone(
      request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DeploymentClient.getFrameworkDeployment`.
    func getFrameworkDeployment(
      request: GetFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkDeployment

    /// See `DeploymentClient.listFrameworkDeployments`.
    func listFrameworkDeployments(
      request: ListFrameworkDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkDeploymentsResponse

    /// See `DeploymentClient.getCloudControlDeployment`.
    func getCloudControlDeployment(
      request: GetCloudControlDeploymentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.CloudControlDeployment

    /// See `DeploymentClient.listCloudControlDeployments`.
    func listCloudControlDeployments(
      request: ListCloudControlDeploymentsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlDeploymentsResponse

    /// See `DeploymentClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DeploymentClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DeploymentClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DeploymentClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DeploymentClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DeploymentProtocol {
  public func createFrameworkDeployment(request: CreateFrameworkDeploymentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createFrameworkDeployment(request: request, options: .init())
  }

  public func createFrameworkDeployment(
    request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createFrameworkDeploymentPollingUntilDone(request: CreateFrameworkDeploymentRequest)
    async throws -> FrameworkDeployment
  {
    return try await self.createFrameworkDeploymentPollingUntilDone(
      request: request, options: .init())
  }

  public func createFrameworkDeploymentPollingUntilDone(
    request: CreateFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> FrameworkDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createFrameworkDeploymentPollingUntilDone(
    parent: Swift.String,
    frameworkDeployment: FrameworkDeployment?,
    frameworkDeploymentId: Swift.String,
  ) async throws -> FrameworkDeployment {
    let request = CreateFrameworkDeploymentRequest().with {
      $0.parent = parent
      $0.frameworkDeployment = frameworkDeployment
      $0.frameworkDeploymentId = frameworkDeploymentId
    }
    return try await self.createFrameworkDeploymentPollingUntilDone(request: request)
  }

  public func deleteFrameworkDeployment(request: DeleteFrameworkDeploymentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteFrameworkDeployment(request: request, options: .init())
  }

  public func deleteFrameworkDeployment(
    request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteFrameworkDeploymentPollingUntilDone(request: DeleteFrameworkDeploymentRequest)
    async throws
  {
    try await self.deleteFrameworkDeploymentPollingUntilDone(request: request, options: .init())
  }

  public func deleteFrameworkDeploymentPollingUntilDone(
    request: DeleteFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteFrameworkDeploymentPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteFrameworkDeploymentRequest().with {
      $0.name = name
    }
    try await self.deleteFrameworkDeploymentPollingUntilDone(request: request)
  }

  public func getFrameworkDeployment(request: GetFrameworkDeploymentRequest) async throws
    -> GoogleCloudSecurityComplianceV1.FrameworkDeployment
  {
    try await self.getFrameworkDeployment(request: request, options: .init())
  }

  public func getFrameworkDeployment(
    request: GetFrameworkDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getFrameworkDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkDeployment {
    let request = GetFrameworkDeploymentRequest().with {
      $0.name = name
    }
    return try await self.getFrameworkDeployment(request: request)
  }

  public func listFrameworkDeployments(request: ListFrameworkDeploymentsRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListFrameworkDeploymentsResponse
  {
    try await self.listFrameworkDeployments(request: request, options: .init())
  }

  public func listFrameworkDeployments(
    request: ListFrameworkDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkDeploymentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFrameworkDeploymentsByItems(
    request: ListFrameworkDeploymentsRequest
  ) -> some AsyncSequence<FrameworkDeployment, any Swift.Error> & Sendable {
    self.listFrameworkDeploymentsByItems(request: request, options: .init())
  }

  /// Lists the framework deployments in a given parent resource.
  ///
  /// @Snippet(path: "Deployment_ListFrameworkDeployments")
  public func listFrameworkDeploymentsByItems(
    request: ListFrameworkDeploymentsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<FrameworkDeployment, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListFrameworkDeploymentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listFrameworkDeployments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listFrameworkDeploymentsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<FrameworkDeployment, any Swift.Error> & Sendable {
    let request = ListFrameworkDeploymentsRequest().with {
      $0.parent = parent
    }
    return self.listFrameworkDeploymentsByItems(request: request)
  }

  public func getCloudControlDeployment(request: GetCloudControlDeploymentRequest) async throws
    -> GoogleCloudSecurityComplianceV1.CloudControlDeployment
  {
    try await self.getCloudControlDeployment(request: request, options: .init())
  }

  public func getCloudControlDeployment(
    request: GetCloudControlDeploymentRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControlDeployment {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getCloudControlDeployment(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.CloudControlDeployment {
    let request = GetCloudControlDeploymentRequest().with {
      $0.name = name
    }
    return try await self.getCloudControlDeployment(request: request)
  }

  public func listCloudControlDeployments(request: ListCloudControlDeploymentsRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListCloudControlDeploymentsResponse
  {
    try await self.listCloudControlDeployments(request: request, options: .init())
  }

  public func listCloudControlDeployments(
    request: ListCloudControlDeploymentsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListCloudControlDeploymentsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listCloudControlDeploymentsByItems(
    request: ListCloudControlDeploymentsRequest
  ) -> some AsyncSequence<CloudControlDeployment, any Swift.Error> & Sendable {
    self.listCloudControlDeploymentsByItems(request: request, options: .init())
  }

  /// Lists the cloud conrol deployments in a given parent resource.
  ///
  /// @Snippet(path: "Deployment_ListCloudControlDeployments")
  public func listCloudControlDeploymentsByItems(
    request: ListCloudControlDeploymentsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<CloudControlDeployment, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListCloudControlDeploymentsResponse in
      var request = request
      request.pageToken = token
      return try await self.listCloudControlDeployments(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listCloudControlDeploymentsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<CloudControlDeployment, any Swift.Error> & Sendable {
    let request = ListCloudControlDeploymentsRequest().with {
      $0.parent = parent
    }
    return self.listCloudControlDeploymentsByItems(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Deployment_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Deployment_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
