// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// A finding is a record of assessment data like security, risk, health, or
/// privacy.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum FindingClass: Codable, Equatable, Hashable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// The activity is unwanted or malicious.
  case threat
  /// A potential weakness in software that increases risk to
  /// confidentiality, integrity, and availability.
  case vulnerability
  /// A potential weakness in a cloud resource or asset configuration that
  /// increases risk.
  case misconfiguration
  /// A security observation that is for informational purposes.
  case observation
  /// An error that prevents Security Command Center from functioning properly.
  case sccError
  /// A potential security risk that's due to a change in the security
  /// posture.
  case postureViolation
  /// A combination of security issues that represent a more severe
  /// security problem when taken together.
  case toxicCombination
  /// A potential security risk to data assets that contain sensitive
  /// data.
  case sensitiveDataRisk
  /// A resource or resource group where high risk attack paths
  /// converge, based on attack path simulations (APS).
  case chokepoint
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .threat: return 1
    case .vulnerability: return 2
    case .misconfiguration: return 3
    case .observation: return 4
    case .sccError: return 5
    case .postureViolation: return 6
    case .toxicCombination: return 7
    case .sensitiveDataRisk: return 8
    case .chokepoint: return 9
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "FINDING_CLASS_UNSPECIFIED"
    case .threat: return "THREAT"
    case .vulnerability: return "VULNERABILITY"
    case .misconfiguration: return "MISCONFIGURATION"
    case .observation: return "OBSERVATION"
    case .sccError: return "SCC_ERROR"
    case .postureViolation: return "POSTURE_VIOLATION"
    case .toxicCombination: return "TOXIC_COMBINATION"
    case .sensitiveDataRisk: return "SENSITIVE_DATA_RISK"
    case .chokepoint: return "CHOKEPOINT"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FindingClass/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "FINDING_CLASS_UNSPECIFIED": self = .unspecified
    case "THREAT": self = .threat
    case "VULNERABILITY": self = .vulnerability
    case "MISCONFIGURATION": self = .misconfiguration
    case "OBSERVATION": self = .observation
    case "SCC_ERROR": self = .sccError
    case "POSTURE_VIOLATION": self = .postureViolation
    case "TOXIC_COMBINATION": self = .toxicCombination
    case "SENSITIVE_DATA_RISK": self = .sensitiveDataRisk
    case "CHOKEPOINT": self = .chokepoint
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FindingClass/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .threat
    case 2: self = .vulnerability
    case 3: self = .misconfiguration
    case 4: self = .observation
    case 5: self = .sccError
    case 6: self = .postureViolation
    case 7: self = .toxicCombination
    case 8: self = .sensitiveDataRisk
    case 9: self = .chokepoint
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("FINDING_CLASS_UNSPECIFIED")
    case .threat: return try container.encode("THREAT")
    case .vulnerability: return try container.encode("VULNERABILITY")
    case .misconfiguration: return try container.encode("MISCONFIGURATION")
    case .observation: return try container.encode("OBSERVATION")
    case .sccError: return try container.encode("SCC_ERROR")
    case .postureViolation: return try container.encode("POSTURE_VIOLATION")
    case .toxicCombination: return try container.encode("TOXIC_COMBINATION")
    case .sensitiveDataRisk: return try container.encode("SENSITIVE_DATA_RISK")
    case .chokepoint: return try container.encode("CHOKEPOINT")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
