// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A framework is a collection of cloud controls and regulatory controls
/// that represent security best practices or industry-defined standards such as
/// FedRAMP or NIST.
public struct Framework: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Identifier. The name of the framework, in one of the following
  /// formats:
  /// `organizations/{organization}/locations/{location}/frameworks/{framework}`
  /// or
  /// `projects/{project}/locations/{location}/frameworks/{framework}`.
  ///
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Output only. The major version of the framework, which is incremented in
  /// ascending order.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// Optional. The friendly name of the framework. The maximum length is 200
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the framework. The maximum length is 2000
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The type of framework.
  public var type: Framework.FrameworkType = Framework.FrameworkType()

  /// Optional. The cloud control details that are directly added without any
  /// grouping in the framework.
  public var cloudControlDetails: [CloudControlDetails] = []

  /// Optional. The category of the framework.
  public var category: [FrameworkCategory] = []

  /// Output only. The cloud providers that are supported by the framework.
  public var supportedCloudProviders: [CloudProvider] = []

  /// Output only. The target resource types that are supported by the framework.
  public var supportedTargetResourceTypes: [TargetResourceType] = []

  /// Output only. The supported enforcement modes of the framework.
  public var supportedEnforcementModes: [EnforcementMode] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Framework`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Framework().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let majorRevisionId = CodingKeys(stringValue: "majorRevisionId")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let type = CodingKeys(stringValue: "type")
    static let cloudControlDetails = CodingKeys(stringValue: "cloudControlDetails")
    static let category = CodingKeys(stringValue: "category")
    static let supportedCloudProviders = CodingKeys(stringValue: "supportedCloudProviders")
    static let supportedTargetResourceTypes = CodingKeys(
      stringValue: "supportedTargetResourceTypes")
    static let supportedEnforcementModes = CodingKeys(stringValue: "supportedEnforcementModes")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "majorRevisionId",
      "displayName",
      "description",
      "type",
      "cloudControlDetails",
      "category",
      "supportedCloudProviders",
      "supportedTargetResourceTypes",
      "supportedEnforcementModes",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .majorRevisionId) {
      self.majorRevisionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Framework.FrameworkType.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(
      [CloudControlDetails].self, forKey: .cloudControlDetails)
    {
      self.cloudControlDetails = value
    }
    if let value = try container.decodeIfPresent([FrameworkCategory].self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(
      [CloudProvider].self, forKey: .supportedCloudProviders)
    {
      self.supportedCloudProviders = value
    }
    if let value = try container.decodeIfPresent(
      [TargetResourceType].self, forKey: .supportedTargetResourceTypes)
    {
      self.supportedTargetResourceTypes = value
    }
    if let value = try container.decodeIfPresent(
      [EnforcementMode].self, forKey: .supportedEnforcementModes)
    {
      self.supportedEnforcementModes = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.cloudControlDetails, forKey: .cloudControlDetails)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.supportedCloudProviders, forKey: .supportedCloudProviders)
    try container.encode(self.supportedTargetResourceTypes, forKey: .supportedTargetResourceTypes)
    try container.encode(self.supportedEnforcementModes, forKey: .supportedEnforcementModes)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of framework.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum FrameworkType: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// A framework that's provided and managed by Google.
    case builtIn
    /// A framework that's created and managed by you.
    case custom
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .builtIn: return 1
      case .custom: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FRAMEWORK_TYPE_UNSPECIFIED"
      case .builtIn: return "BUILT_IN"
      case .custom: return "CUSTOM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FrameworkType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FRAMEWORK_TYPE_UNSPECIFIED": self = .unspecified
      case "BUILT_IN": self = .builtIn
      case "CUSTOM": self = .custom
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FrameworkType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .builtIn
      case 2: self = .custom
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("FRAMEWORK_TYPE_UNSPECIFIED")
      case .builtIn: return try container.encode("BUILT_IN")
      case .custom: return try container.encode("CUSTOM")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Framework"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
