// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The category for the framework.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum FrameworkCategory: Codable, Equatable, Hashable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// An industry-defined framework.
  case industryDefinedStandard
  /// An Assured Workloads framework.
  case assuredWorkloads
  /// A data security posture framework.
  case dataSecurity
  /// A Google's best practices framework.
  case googleBestPractices
  /// A user-created framework.
  case customFramework
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .industryDefinedStandard: return 1
    case .assuredWorkloads: return 2
    case .dataSecurity: return 3
    case .googleBestPractices: return 4
    case .customFramework: return 5
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "FRAMEWORK_CATEGORY_UNSPECIFIED"
    case .industryDefinedStandard: return "INDUSTRY_DEFINED_STANDARD"
    case .assuredWorkloads: return "ASSURED_WORKLOADS"
    case .dataSecurity: return "DATA_SECURITY"
    case .googleBestPractices: return "GOOGLE_BEST_PRACTICES"
    case .customFramework: return "CUSTOM_FRAMEWORK"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FrameworkCategory/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "FRAMEWORK_CATEGORY_UNSPECIFIED": self = .unspecified
    case "INDUSTRY_DEFINED_STANDARD": self = .industryDefinedStandard
    case "ASSURED_WORKLOADS": self = .assuredWorkloads
    case "DATA_SECURITY": self = .dataSecurity
    case "GOOGLE_BEST_PRACTICES": self = .googleBestPractices
    case "CUSTOM_FRAMEWORK": self = .customFramework
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FrameworkCategory/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .industryDefinedStandard
    case 2: self = .assuredWorkloads
    case 3: self = .dataSecurity
    case 4: self = .googleBestPractices
    case 5: self = .customFramework
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("FRAMEWORK_CATEGORY_UNSPECIFIED")
    case .industryDefinedStandard: return try container.encode("INDUSTRY_DEFINED_STANDARD")
    case .assuredWorkloads: return try container.encode("ASSURED_WORKLOADS")
    case .dataSecurity: return try container.encode("DATA_SECURITY")
    case .googleBestPractices: return try container.encode("GOOGLE_BEST_PRACTICES")
    case .customFramework: return try container.encode("CUSTOM_FRAMEWORK")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
