// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The reference to a framework deployment.
public struct FrameworkDeploymentReference: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The name of the framework deployment, in the format
  /// `organizations/{organization}/locations/{location}/frameworkDeployments/{framework_deployment}`
  /// or
  /// `projects/{project}/locations/{location}/frameworkDeployments/{framework_deployment}`.
  /// The only supported location is `global`.
  public var frameworkDeployment: Swift.String = Swift.String()

  /// Optional. The reference to the framework that this deployment is for.
  /// For example:
  ///
  /// ```
  /// {
  ///   framework:
  ///   "organizations/{organization}/locations/{location}/frameworks/{framework}",
  ///   major_revision_id: 1
  /// }
  /// ```
  ///
  /// The only supported location is `global`.
  public var frameworkReference: FrameworkReference? = nil

  /// Optional. The display name of the framework that this framework deployment
  /// is for.
  public var frameworkDisplayName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FrameworkDeploymentReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkDeploymentReference().with { $0.frameworkDeployment = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let frameworkDeployment = CodingKeys(stringValue: "frameworkDeployment")
    static let frameworkReference = CodingKeys(stringValue: "frameworkReference")
    static let frameworkDisplayName = CodingKeys(stringValue: "frameworkDisplayName")

    static let _knownKeys: Set<Swift.String> = [
      "frameworkDeployment",
      "frameworkReference",
      "frameworkDisplayName",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameworkDeployment) {
      self.frameworkDeployment = value
    }
    self.frameworkReference = try container.decodeIfPresent(
      FrameworkReference.self, forKey: .frameworkReference)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameworkDisplayName) {
      self.frameworkDisplayName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.frameworkDeployment, forKey: .frameworkDeployment)
    try container.encodeIfPresent(self.frameworkReference, forKey: .frameworkReference)
    try container.encode(self.frameworkDisplayName, forKey: .frameworkDisplayName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `FrameworkDeploymentReference`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkDeploymentReference"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkDeploymentReference"
  }

  /// Initialize an instance of `FrameworkDeploymentReference` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkDeploymentReference"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `FrameworkDeploymentReference` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
