// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A framework audit.
public struct FrameworkAudit: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The name of the framework audit.
  public var name: Swift.String = Swift.String()

  /// Output only. The ID of the framework audit.
  public var frameworkAuditId: Swift.String = Swift.String()

  /// Output only. The compliance framework used for the audit.
  public var complianceFramework: Swift.String = Swift.String()

  /// Output only. The scope of the audit.
  public var scope: Swift.String = Swift.String()

  /// Required. The destination for the audit reports.
  public var frameworkAuditDestination: FrameworkAuditDestination? = nil

  /// Output only. The time that the audit started.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time that the audit finished.
  public var finishTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The overall compliance state of the audit.
  public var complianceState: ComplianceState = ComplianceState()

  /// Output only. The summary of the report.
  public var reportSummary: ReportSummary? = nil

  /// Optional. The details for the cloud control groups within this audit.
  public var cloudControlGroupAuditDetails: [CloudControlGroupAuditDetails] = []

  /// Optional. The details for the cloud controls within this audit.
  public var cloudControlAuditDetails: [CloudControlAuditDetails] = []

  /// Output only. The ID of the long-running operation.
  public var operationId: Swift.String = Swift.String()

  /// Output only. The framework audit state of the audit.
  public var state: FrameworkAudit.State = FrameworkAudit.State()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FrameworkAudit`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkAudit().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let frameworkAuditId = CodingKeys(stringValue: "frameworkAuditId")
    static let complianceFramework = CodingKeys(stringValue: "complianceFramework")
    static let scope = CodingKeys(stringValue: "scope")
    static let frameworkAuditDestination = CodingKeys(stringValue: "frameworkAuditDestination")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let finishTime = CodingKeys(stringValue: "finishTime")
    static let complianceState = CodingKeys(stringValue: "complianceState")
    static let reportSummary = CodingKeys(stringValue: "reportSummary")
    static let cloudControlGroupAuditDetails = CodingKeys(
      stringValue: "cloudControlGroupAuditDetails")
    static let cloudControlAuditDetails = CodingKeys(stringValue: "cloudControlAuditDetails")
    static let operationId = CodingKeys(stringValue: "operationId")
    static let state = CodingKeys(stringValue: "state")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "frameworkAuditId",
      "complianceFramework",
      "scope",
      "frameworkAuditDestination",
      "startTime",
      "finishTime",
      "complianceState",
      "reportSummary",
      "cloudControlGroupAuditDetails",
      "cloudControlAuditDetails",
      "operationId",
      "state",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameworkAuditId) {
      self.frameworkAuditId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .complianceFramework) {
      self.complianceFramework = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    self.frameworkAuditDestination = try container.decodeIfPresent(
      FrameworkAuditDestination.self, forKey: .frameworkAuditDestination)
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.finishTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .finishTime)
    if let value = try container.decodeIfPresent(ComplianceState.self, forKey: .complianceState) {
      self.complianceState = value
    }
    self.reportSummary = try container.decodeIfPresent(ReportSummary.self, forKey: .reportSummary)
    if let value = try container.decodeIfPresent(
      [CloudControlGroupAuditDetails].self, forKey: .cloudControlGroupAuditDetails)
    {
      self.cloudControlGroupAuditDetails = value
    }
    if let value = try container.decodeIfPresent(
      [CloudControlAuditDetails].self, forKey: .cloudControlAuditDetails)
    {
      self.cloudControlAuditDetails = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationId) {
      self.operationId = value
    }
    if let value = try container.decodeIfPresent(FrameworkAudit.State.self, forKey: .state) {
      self.state = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.frameworkAuditId, forKey: .frameworkAuditId)
    try container.encode(self.complianceFramework, forKey: .complianceFramework)
    try container.encode(self.scope, forKey: .scope)
    try container.encodeIfPresent(
      self.frameworkAuditDestination, forKey: .frameworkAuditDestination)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.finishTime, forKey: .finishTime)
    try container.encode(self.complianceState, forKey: .complianceState)
    try container.encodeIfPresent(self.reportSummary, forKey: .reportSummary)
    try container.encode(self.cloudControlGroupAuditDetails, forKey: .cloudControlGroupAuditDetails)
    try container.encode(self.cloudControlAuditDetails, forKey: .cloudControlAuditDetails)
    try container.encode(self.operationId, forKey: .operationId)
    try container.encode(self.state, forKey: .state)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The state of the framework audit.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// The audit is scheduled.
    case scheduled
    /// The audit is running.
    case running
    /// The audit results are being uploaded.
    case uploading
    /// The audit failed.
    case failed
    /// The audit completed successfully.
    case succeeded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .scheduled: return 1
      case .running: return 2
      case .uploading: return 3
      case .failed: return 4
      case .succeeded: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .scheduled: return "SCHEDULED"
      case .running: return "RUNNING"
      case .uploading: return "UPLOADING"
      case .failed: return "FAILED"
      case .succeeded: return "SUCCEEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SCHEDULED": self = .scheduled
      case "RUNNING": self = .running
      case "UPLOADING": self = .uploading
      case "FAILED": self = .failed
      case "SUCCEEDED": self = .succeeded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .scheduled
      case 2: self = .running
      case 3: self = .uploading
      case 4: self = .failed
      case 5: self = .succeeded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .scheduled: return try container.encode("SCHEDULED")
      case .running: return try container.encode("RUNNING")
      case .uploading: return try container.encode("UPLOADING")
      case .failed: return try container.encode("FAILED")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkAudit"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
