// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Framework deployments represent the assignment of a framework to a target
/// resource. Supported target resources are organizations, folders, and
/// projects.
public struct FrameworkDeployment: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the framework deployment, in the format
  /// `organizations/{organization}/locations/{location}/frameworkDeployments/{framework_deployment}`
  /// or
  /// `projects/{project}/locations/{location}/frameworkDeployments/{framework_deployment}`.
  /// The only supported location is `global`.
  public var name: Swift.String = Swift.String()

  /// Required. The details of the target resource that you want to deploy the
  /// framework to. You can specify an existing resource, or create a new one.
  public var targetResourceConfig: TargetResourceConfig? = nil

  /// Output only. The target resource to deploy the framework to, in one  the
  /// following formats:
  ///
  /// - `organizations/{organizationID}`
  /// - `folders/{folderID}`
  /// - `projects/{projectID}`
  public var computedTargetResource: Swift.String = Swift.String()

  /// Required. A reference to the framework that you're deploying.
  public var framework: FrameworkReference? = nil

  /// Optional. A user-provided description of the framework deployment.
  public var description: Swift.String = Swift.String()

  /// Required. The deployment mode and parameters for each of the cloud controls
  /// in the framework. Every cloud control in the framework includes metadata.
  public var cloudControlMetadata: [CloudControlMetadata] = []

  /// Output only. The state for the framework deployment.
  public var deploymentState: DeploymentState = DeploymentState()

  /// Output only. The time at which the resource was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the resource last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. To prevent concurrent updates from overwriting each other, always
  /// provide the `etag` when you update a framework deployment. You can also
  /// provide the `etag` when you delete a framework deployment, to help
  /// ensure that you're deleting the intended version of the
  /// framework deployment.
  public var etag: Swift.String = Swift.String()

  /// Output only. The display name of the target resource.
  public var targetResourceDisplayName: Swift.String = Swift.String()

  /// Output only. The references to the cloud control deployments. The reference
  /// includes all the cloud control deployments that are in the framework or in
  /// a cloud control group.
  ///
  /// For example, if a framework deployment deploys two
  /// cloud controls, `cc-deployment-1` and `cc-deployment-2`, then the
  /// references are:
  ///
  /// ```
  /// {
  ///  cloud_control_deployment_reference: {
  ///    cloud_control_deployment:
  ///    "organizations/{organization}/locations/{location}/cloudControlDeployments/cc-deployment-1"
  ///  },
  ///  cloud_control_deployment_reference: {
  ///   cloud_control_deployment:
  ///   "organizations/{organization}/locations/{location}/cloudControlDeployments/cc-deployment-2"
  ///  }
  /// ```
  public var cloudControlDeploymentReferences: [CloudControlDeploymentReference] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FrameworkDeployment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkDeployment().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let targetResourceConfig = CodingKeys(stringValue: "targetResourceConfig")
    static let computedTargetResource = CodingKeys(stringValue: "computedTargetResource")
    static let framework = CodingKeys(stringValue: "framework")
    static let description = CodingKeys(stringValue: "description")
    static let cloudControlMetadata = CodingKeys(stringValue: "cloudControlMetadata")
    static let deploymentState = CodingKeys(stringValue: "deploymentState")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let etag = CodingKeys(stringValue: "etag")
    static let targetResourceDisplayName = CodingKeys(stringValue: "targetResourceDisplayName")
    static let cloudControlDeploymentReferences = CodingKeys(
      stringValue: "cloudControlDeploymentReferences")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "targetResourceConfig",
      "computedTargetResource",
      "framework",
      "description",
      "cloudControlMetadata",
      "deploymentState",
      "createTime",
      "updateTime",
      "etag",
      "targetResourceDisplayName",
      "cloudControlDeploymentReferences",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.targetResourceConfig = try container.decodeIfPresent(
      TargetResourceConfig.self, forKey: .targetResourceConfig)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .computedTargetResource)
    {
      self.computedTargetResource = value
    }
    self.framework = try container.decodeIfPresent(FrameworkReference.self, forKey: .framework)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(
      [CloudControlMetadata].self, forKey: .cloudControlMetadata)
    {
      self.cloudControlMetadata = value
    }
    if let value = try container.decodeIfPresent(DeploymentState.self, forKey: .deploymentState) {
      self.deploymentState = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .targetResourceDisplayName)
    {
      self.targetResourceDisplayName = value
    }
    if let value = try container.decodeIfPresent(
      [CloudControlDeploymentReference].self, forKey: .cloudControlDeploymentReferences)
    {
      self.cloudControlDeploymentReferences = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.targetResourceConfig, forKey: .targetResourceConfig)
    try container.encode(self.computedTargetResource, forKey: .computedTargetResource)
    try container.encodeIfPresent(self.framework, forKey: .framework)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.cloudControlMetadata, forKey: .cloudControlMetadata)
    try container.encode(self.deploymentState, forKey: .deploymentState)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.targetResourceDisplayName, forKey: .targetResourceDisplayName)
    try container.encode(
      self.cloudControlDeploymentReferences, forKey: .cloudControlDeploymentReferences)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkDeployment"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
