// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The response message for [GetFrameworkComplianceReport][].
public struct FrameworkComplianceReport: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the framework.
  public var framework: Swift.String = Swift.String()

  /// The description of the framework.
  public var frameworkDescription: Swift.String = Swift.String()

  /// Output only. The last updated time of the report.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// The control assessment details of the framework.
  public var controlAssessmentDetails: ControlAssessmentDetails? = nil

  /// The type of framework.
  public var frameworkType: Framework.FrameworkType = Framework.FrameworkType()

  /// The list of cloud providers supported by the framework.
  public var supportedCloudProviders: [CloudProvider] = []

  /// The list of framework categories supported.
  public var frameworkCategories: [FrameworkCategory] = []

  /// Optional. The display name for the framework.
  public var frameworkDisplayName: Swift.String = Swift.String()

  /// Identifier. The name of the framework compliance report.
  public var name: Swift.String = Swift.String()

  /// The latest major revision ID of the framework.
  public var majorRevisionId: Swift.Int64 = Swift.Int64()

  /// The latest minor revision ID of the latest major revision of the framework.
  public var minorRevisionId: Swift.Int64 = Swift.Int64()

  /// The target resource details of the framework.
  public var targetResourceDetails: [TargetResourceDetails] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FrameworkComplianceReport`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FrameworkComplianceReport().with { $0.framework = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let framework = CodingKeys(stringValue: "framework")
    static let frameworkDescription = CodingKeys(stringValue: "frameworkDescription")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let controlAssessmentDetails = CodingKeys(stringValue: "controlAssessmentDetails")
    static let frameworkType = CodingKeys(stringValue: "frameworkType")
    static let supportedCloudProviders = CodingKeys(stringValue: "supportedCloudProviders")
    static let frameworkCategories = CodingKeys(stringValue: "frameworkCategories")
    static let frameworkDisplayName = CodingKeys(stringValue: "frameworkDisplayName")
    static let name = CodingKeys(stringValue: "name")
    static let majorRevisionId = CodingKeys(stringValue: "majorRevisionId")
    static let minorRevisionId = CodingKeys(stringValue: "minorRevisionId")
    static let targetResourceDetails = CodingKeys(stringValue: "targetResourceDetails")

    static let _knownKeys: Set<Swift.String> = [
      "framework",
      "frameworkDescription",
      "updateTime",
      "controlAssessmentDetails",
      "frameworkType",
      "supportedCloudProviders",
      "frameworkCategories",
      "frameworkDisplayName",
      "name",
      "majorRevisionId",
      "minorRevisionId",
      "targetResourceDetails",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .framework) {
      self.framework = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameworkDescription) {
      self.frameworkDescription = value
    }
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    self.controlAssessmentDetails = try container.decodeIfPresent(
      ControlAssessmentDetails.self, forKey: .controlAssessmentDetails)
    if let value = try container.decodeIfPresent(
      Framework.FrameworkType.self, forKey: .frameworkType)
    {
      self.frameworkType = value
    }
    if let value = try container.decodeIfPresent(
      [CloudProvider].self, forKey: .supportedCloudProviders)
    {
      self.supportedCloudProviders = value
    }
    if let value = try container.decodeIfPresent(
      [FrameworkCategory].self, forKey: .frameworkCategories)
    {
      self.frameworkCategories = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameworkDisplayName) {
      self.frameworkDisplayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .majorRevisionId) {
      self.majorRevisionId = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minorRevisionId) {
      self.minorRevisionId = value
    }
    if let value = try container.decodeIfPresent(
      [TargetResourceDetails].self, forKey: .targetResourceDetails)
    {
      self.targetResourceDetails = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.framework, forKey: .framework)
    try container.encode(self.frameworkDescription, forKey: .frameworkDescription)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.controlAssessmentDetails, forKey: .controlAssessmentDetails)
    try container.encode(self.frameworkType, forKey: .frameworkType)
    try container.encode(self.supportedCloudProviders, forKey: .supportedCloudProviders)
    try container.encode(self.frameworkCategories, forKey: .frameworkCategories)
    try container.encode(self.frameworkDisplayName, forKey: .frameworkDisplayName)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.majorRevisionId, forKey: .majorRevisionId)
    try container.encode(self.minorRevisionId, forKey: .minorRevisionId)
    try container.encode(self.targetResourceDetails, forKey: .targetResourceDetails)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `FrameworkComplianceReport`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkComplianceReport"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkComplianceReport"
  }

  /// Initialize an instance of `FrameworkComplianceReport` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.FrameworkComplianceReport"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `FrameworkComplianceReport` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
