// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The response message for [GenerateFrameworkAuditScopeReport][].
public struct GenerateFrameworkAuditScopeReportResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the audit report, in the format that was
  /// given in the request.
  public var name: Swift.String = Swift.String()

  /// Required. The compliance framework that the audit scope report is generated
  /// for.
  public var complianceFramework: Swift.String = Swift.String()

  /// The set of options that the audit scope report is exported in.
  public var auditReport: AuditReportOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GenerateFrameworkAuditScopeReportResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateFrameworkAuditScopeReportResponse().with { $0.scopeReportContents = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scopeReportContents = CodingKeys(stringValue: "scopeReportContents")
    static let name = CodingKeys(stringValue: "name")
    static let complianceFramework = CodingKeys(stringValue: "complianceFramework")

    static let _knownKeys: Set<Swift.String> = [
      "scopeReportContents",
      "name",
      "complianceFramework",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .complianceFramework) {
      self.complianceFramework = value
    }

    var auditReport: AuditReportOneOf? = nil
    let auditReportCheckAndSet = {
      if auditReport != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'auditReport'"))
      }
      auditReport = $0
    }
    if let scopeReportContents = try container.decodeIfPresent(
      Foundation.Data.self, forKey: .scopeReportContents)
    {
      try auditReportCheckAndSet(.scopeReportContents(scopeReportContents))
    }
    self.auditReport = auditReport
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.complianceFramework, forKey: .complianceFramework)

    if let choice = self.auditReport {
      switch choice {
      case .scopeReportContents(let value):
        try container.encode(value, forKey: .scopeReportContents)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The set of options that the audit scope report is exported in.
  public enum AuditReportOneOf: Codable, Equatable, Sendable {
    /// The audit scope report content in byte format.
    case scopeReportContents(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.GenerateFrameworkAuditScopeReportResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
