// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleCloudLocation
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Service describing handlers for resources
///
/// @Snippet(path: "MonitoringQuickstart")
public final class MonitoringClient: Clients.MonitoringProtocol, Sendable {
  let inner: any Clients.MonitoringStub

  /// Creates a new `MonitoringClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.MonitoringStub = try Clients.MonitoringTransport(options)
    inner = Clients.MonitoringRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MonitoringLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists the framework compliance summary for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListFrameworkComplianceSummaries")
  public func listFrameworkComplianceSummaries(
    request: ListFrameworkComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse {
    try await self.inner.listFrameworkComplianceSummaries(request: request, options: options)
  }

  /// Lists the finding summary by category for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListFindingSummaries")
  public func listFindingSummaries(
    request: ListFindingSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse {
    try await self.inner.listFindingSummaries(request: request, options: options)
  }

  /// Fetches the framework compliance report for a given scope.
  ///
  /// @Snippet(path: "Monitoring_FetchFrameworkComplianceReport")
  public func fetchFrameworkComplianceReport(
    request: FetchFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport {
    try await self.inner.fetchFrameworkComplianceReport(request: request, options: options)
  }

  /// Lists the control compliance summary for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListControlComplianceSummaries")
  public func listControlComplianceSummaries(
    request: ListControlComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse {
    try await self.inner.listControlComplianceSummaries(request: request, options: options)
  }

  /// Gets the aggregated compliance report over time for a given scope.
  ///
  /// @Snippet(path: "Monitoring_AggregateFrameworkComplianceReport")
  public func aggregateFrameworkComplianceReport(
    request: AggregateFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse {
    try await self.inner.aggregateFrameworkComplianceReport(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Monitoring_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Monitoring_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Monitoring_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Monitoring_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Monitoring_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Monitoring_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `MonitoringClient`.
  ///
  /// To mock `MonitoringClient` change your functions to receive
  /// `some MonitoringProtocol` or `any MonitoringProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MonitoringProtocol: Sendable {
    /// See `MonitoringClient.listFrameworkComplianceSummaries`.
    func listFrameworkComplianceSummaries(
      request: ListFrameworkComplianceSummariesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse

    /// See `MonitoringClient.listFindingSummaries`.
    func listFindingSummaries(
      request: ListFindingSummariesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse

    /// See `MonitoringClient.fetchFrameworkComplianceReport`.
    func fetchFrameworkComplianceReport(
      request: FetchFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport

    /// See `MonitoringClient.listControlComplianceSummaries`.
    func listControlComplianceSummaries(
      request: ListControlComplianceSummariesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse

    /// See `MonitoringClient.aggregateFrameworkComplianceReport`.
    func aggregateFrameworkComplianceReport(
      request: AggregateFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse

    /// See `MonitoringClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `MonitoringClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `MonitoringClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `MonitoringClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `MonitoringClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.MonitoringProtocol {
  public func listFrameworkComplianceSummaries(request: ListFrameworkComplianceSummariesRequest)
    async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse
  {
    try await self.listFrameworkComplianceSummaries(request: request, options: .init())
  }

  public func listFrameworkComplianceSummaries(
    request: ListFrameworkComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFrameworkComplianceSummariesByItems(
    request: ListFrameworkComplianceSummariesRequest
  ) -> some AsyncSequence<FrameworkComplianceSummary, any Swift.Error> & Sendable {
    self.listFrameworkComplianceSummariesByItems(request: request, options: .init())
  }

  /// Lists the framework compliance summary for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListFrameworkComplianceSummaries")
  public func listFrameworkComplianceSummariesByItems(
    request: ListFrameworkComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<FrameworkComplianceSummary, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListFrameworkComplianceSummariesResponse in
      var request = request
      request.pageToken = token
      return try await self.listFrameworkComplianceSummaries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listFrameworkComplianceSummariesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<FrameworkComplianceSummary, any Swift.Error> & Sendable {
    let request = ListFrameworkComplianceSummariesRequest().with {
      $0.parent = parent
    }
    return self.listFrameworkComplianceSummariesByItems(request: request)
  }

  public func listFindingSummaries(request: ListFindingSummariesRequest) async throws
    -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse
  {
    try await self.listFindingSummaries(request: request, options: .init())
  }

  public func listFindingSummaries(
    request: ListFindingSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listFindingSummariesByItems(
    request: ListFindingSummariesRequest
  ) -> some AsyncSequence<FindingSummary, any Swift.Error> & Sendable {
    self.listFindingSummariesByItems(request: request, options: .init())
  }

  /// Lists the finding summary by category for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListFindingSummaries")
  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func listFindingSummariesByItems(
    request: ListFindingSummariesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<FindingSummary, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListFindingSummariesResponse in
      var request = request
      request.pageToken = token
      return try await self.listFindingSummaries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func listFindingSummariesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<FindingSummary, any Swift.Error> & Sendable {
    let request = ListFindingSummariesRequest().with {
      $0.parent = parent
    }
    return self.listFindingSummariesByItems(request: request)
  }

  public func fetchFrameworkComplianceReport(request: FetchFrameworkComplianceReportRequest)
    async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport
  {
    try await self.fetchFrameworkComplianceReport(request: request, options: .init())
  }

  public func fetchFrameworkComplianceReport(
    request: FetchFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport {
    throw GoogleGax.RequestError.unimplemented
  }

  public func fetchFrameworkComplianceReport(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.FrameworkComplianceReport {
    let request = FetchFrameworkComplianceReportRequest().with {
      $0.name = name
    }
    return try await self.fetchFrameworkComplianceReport(request: request)
  }

  public func listControlComplianceSummaries(request: ListControlComplianceSummariesRequest)
    async throws -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse
  {
    try await self.listControlComplianceSummaries(request: request, options: .init())
  }

  public func listControlComplianceSummaries(
    request: ListControlComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listControlComplianceSummariesByItems(
    request: ListControlComplianceSummariesRequest
  ) -> some AsyncSequence<ControlComplianceSummary, any Swift.Error> & Sendable {
    self.listControlComplianceSummariesByItems(request: request, options: .init())
  }

  /// Lists the control compliance summary for a given scope.
  ///
  /// @Snippet(path: "Monitoring_ListControlComplianceSummaries")
  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func listControlComplianceSummariesByItems(
    request: ListControlComplianceSummariesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ControlComplianceSummary, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws
        -> GoogleCloudSecurityComplianceV1.ListControlComplianceSummariesResponse in
      var request = request
      request.pageToken = token
      return try await self.listControlComplianceSummaries(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func listControlComplianceSummariesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ControlComplianceSummary, any Swift.Error> & Sendable {
    let request = ListControlComplianceSummariesRequest().with {
      $0.parent = parent
    }
    return self.listControlComplianceSummariesByItems(request: request)
  }

  public func aggregateFrameworkComplianceReport(request: AggregateFrameworkComplianceReportRequest)
    async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse
  {
    try await self.aggregateFrameworkComplianceReport(request: request, options: .init())
  }

  public func aggregateFrameworkComplianceReport(
    request: AggregateFrameworkComplianceReportRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func aggregateFrameworkComplianceReport(
    name: Swift.String,
  ) async throws -> GoogleCloudSecurityComplianceV1.AggregateFrameworkComplianceReportResponse {
    let request = AggregateFrameworkComplianceReportRequest().with {
      $0.name = name
    }
    return try await self.aggregateFrameworkComplianceReport(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    self.listLocationsByItems(request: request, options: .init())
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "Monitoring_ListLocations")
  public func listLocationsByItems(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleCloudLocation.Location, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Monitoring_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
