// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The observation details for a finding.
public struct ObservationDetails: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The current value.
  public var currentValue: Swift.String = Swift.String()

  /// Optional. The expected value.
  public var expectedValue: Swift.String = Swift.String()

  /// Output only. Any guidance for the observation.
  public var guidance: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ObservationDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ObservationDetails().with { $0.currentValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let currentValue = CodingKeys(stringValue: "currentValue")
    static let expectedValue = CodingKeys(stringValue: "expectedValue")
    static let guidance = CodingKeys(stringValue: "guidance")

    static let _knownKeys: Set<Swift.String> = [
      "currentValue",
      "expectedValue",
      "guidance",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .currentValue) {
      self.currentValue = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .expectedValue) {
      self.expectedValue = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .guidance) {
      self.guidance = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.currentValue, forKey: .currentValue)
    try container.encode(self.expectedValue, forKey: .expectedValue)
    try container.encode(self.guidance, forKey: .guidance)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type URL for `ObservationDetails`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ObservationDetails"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ObservationDetails"
  }

  /// Initialize an instance of `ObservationDetails` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ObservationDetails"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ObservationDetails` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
