// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The possible parameter value types.
public struct ParamValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of possible parameter value types.
  public var kind: KindOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ParamValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParamValue().with { $0.stringValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let stringValue = CodingKeys(stringValue: "stringValue")
    static let boolValue = CodingKeys(stringValue: "boolValue")
    static let stringListValue = CodingKeys(stringValue: "stringListValue")
    static let numberValue = CodingKeys(stringValue: "numberValue")
    static let oneofValue = CodingKeys(stringValue: "oneofValue")

    static let _knownKeys: Set<Swift.String> = [
      "stringValue",
      "boolValue",
      "stringListValue",
      "numberValue",
      "oneofValue",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var kind: KindOneOf? = nil
    let kindCheckAndSet = {
      if kind != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'kind'"
          ))
      }
      kind = $0
    }
    if let stringValue = try container.decodeIfPresent(Swift.String.self, forKey: .stringValue) {
      try kindCheckAndSet(.stringValue(stringValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try kindCheckAndSet(.boolValue(boolValue))
    }
    if let stringListValue = try container.decodeIfPresent(
      StringList.self, forKey: .stringListValue)
    {
      try kindCheckAndSet(.stringListValue(stringListValue))
    }
    if let numberValue = try container.decodeIfPresent(Swift.Double.self, forKey: .numberValue) {
      try kindCheckAndSet(.numberValue(numberValue))
    }
    if let oneofValue = try container.decodeIfPresent(Parameter.self, forKey: .oneofValue) {
      try kindCheckAndSet(.oneofValue(oneofValue))
    }
    self.kind = kind
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.kind {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      case .stringListValue(let value):
        try container.encode(value, forKey: .stringListValue)
      case .numberValue(let value):
        try container.encode(value, forKey: .numberValue)
      case .oneofValue(let value):
        try container.encode(value, forKey: .oneofValue)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The list of possible parameter value types.
  public enum KindOneOf: Codable, Equatable, Sendable {
    /// Optional. A string value.
    case stringValue(Swift.String)
    /// Optional. A boolean value.
    case boolValue(Swift.Bool)
    /// Optional. A repeated string.
    indirect case stringListValue(StringList)
    /// Optional. A double value.
    case numberValue(Swift.Double)
    /// Optional. Sub-parameter values.
    indirect case oneofValue(Parameter)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParamValue"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
