// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The parameter specification for the cloud control.
public struct ParameterSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The name of the parameter.
  public var name: Swift.String = Swift.String()

  /// Optional. The friendly name of the parameter. The maximum length is 200
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The description of the parameter. The maximum length is 2000
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Required. Whether the parameter is required.
  public var isRequired: Swift.Bool = Swift.Bool()

  /// Required. The parameter value type.
  public var valueType: ParameterSpec.ValueType = ParameterSpec.ValueType()

  /// Optional. The default value of the parameter.
  public var defaultValue: ParamValue? = nil

  /// Optional. The list of parameter substitutions.
  public var substitutionRules: [ParameterSubstitutionRule] = []

  /// Optional. The parameter specification for `oneOf` attributes.
  public var subParameters: [ParameterSpec] = []

  /// Optional. The permitted set of values for the parameter.
  public var validation: Validation? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ParameterSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ParameterSpec().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let isRequired = CodingKeys(stringValue: "isRequired")
    static let valueType = CodingKeys(stringValue: "valueType")
    static let defaultValue = CodingKeys(stringValue: "defaultValue")
    static let substitutionRules = CodingKeys(stringValue: "substitutionRules")
    static let subParameters = CodingKeys(stringValue: "subParameters")
    static let validation = CodingKeys(stringValue: "validation")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "isRequired",
      "valueType",
      "defaultValue",
      "substitutionRules",
      "subParameters",
      "validation",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isRequired) {
      self.isRequired = value
    }
    if let value = try container.decodeIfPresent(ParameterSpec.ValueType.self, forKey: .valueType) {
      self.valueType = value
    }
    self.defaultValue = try container.decodeIfPresent(ParamValue.self, forKey: .defaultValue)
    if let value = try container.decodeIfPresent(
      [ParameterSubstitutionRule].self, forKey: .substitutionRules)
    {
      self.substitutionRules = value
    }
    if let value = try container.decodeIfPresent([ParameterSpec].self, forKey: .subParameters) {
      self.subParameters = value
    }
    self.validation = try container.decodeIfPresent(Validation.self, forKey: .validation)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.isRequired, forKey: .isRequired)
    try container.encode(self.valueType, forKey: .valueType)
    try container.encodeIfPresent(self.defaultValue, forKey: .defaultValue)
    try container.encode(self.substitutionRules, forKey: .substitutionRules)
    try container.encode(self.subParameters, forKey: .subParameters)
    try container.encodeIfPresent(self.validation, forKey: .validation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of parameter value.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ValueType: Codable, Equatable, Hashable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// A string value.
    case string
    /// A boolean value.
    case boolean
    /// A string list value.
    case stringlist
    /// A numeric value.
    case number
    /// A oneOf value.
    case oneof
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .string: return 3
      case .boolean: return 4
      case .stringlist: return 5
      case .number: return 6
      case .oneof: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VALUE_TYPE_UNSPECIFIED"
      case .string: return "STRING"
      case .boolean: return "BOOLEAN"
      case .stringlist: return "STRINGLIST"
      case .number: return "NUMBER"
      case .oneof: return "ONEOF"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ValueType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VALUE_TYPE_UNSPECIFIED": self = .unspecified
      case "STRING": self = .string
      case "BOOLEAN": self = .boolean
      case "STRINGLIST": self = .stringlist
      case "NUMBER": self = .number
      case "ONEOF": self = .oneof
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ValueType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 3: self = .string
      case 4: self = .boolean
      case 5: self = .stringlist
      case 6: self = .number
      case 7: self = .oneof
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: any Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: any Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VALUE_TYPE_UNSPECIFIED")
      case .string: return try container.encode("STRING")
      case .boolean: return try container.encode("BOOLEAN")
      case .stringlist: return try container.encode("STRINGLIST")
      case .number: return try container.encode("NUMBER")
      case .oneof: return try container.encode("ONEOF")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The type URL for `ParameterSpec`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParameterSpec"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParameterSpec"
  }

  /// Initialize an instance of `ParameterSpec` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.ParameterSpec"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `ParameterSpec` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
