// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A rule in the cloud control.
public struct Rule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The rule description. The maximum length is 2000 characters.
  public var description: Swift.String = Swift.String()

  /// Required. The functionality that's enabled by the rule.
  public var ruleActionTypes: [RuleActionType] = []

  /// The rule implementation.
  public var implementation: ImplementationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Rule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rule().with { $0.celExpression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let celExpression = CodingKeys(stringValue: "celExpression")
    static let description = CodingKeys(stringValue: "description")
    static let ruleActionTypes = CodingKeys(stringValue: "ruleActionTypes")

    static let _knownKeys: Set<Swift.String> = [
      "celExpression",
      "description",
      "ruleActionTypes",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([RuleActionType].self, forKey: .ruleActionTypes) {
      self.ruleActionTypes = value
    }

    var implementation: ImplementationOneOf? = nil
    let implementationCheckAndSet = {
      if implementation != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'implementation'"))
      }
      implementation = $0
    }
    if let celExpression = try container.decodeIfPresent(CELExpression.self, forKey: .celExpression)
    {
      try implementationCheckAndSet(.celExpression(celExpression))
    }
    self.implementation = implementation
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.ruleActionTypes, forKey: .ruleActionTypes)

    if let choice = self.implementation {
      switch choice {
      case .celExpression(let value):
        try container.encode(value, forKey: .celExpression)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The rule implementation.
  public enum ImplementationOneOf: Codable, Equatable, Sendable {
    /// The rule's logic expression in Common Expression Language (CEL).
    indirect case celExpression(CELExpression)
  }

  /// The type URL for `Rule`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Rule"`.
  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Rule"
  }

  /// Initialize an instance of `Rule` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Rule"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `Rule` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
