// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The severity of the finding.
///
/// - Note: Adding cases to this enumeration is not considered a breaking change.
///   Always include an `@unknown default:` case when switching over this type.
///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
///   expecting specific values to remain unparsed; future releases may promote
///   them to named cases.
public enum Severity: Codable, Equatable, Hashable, Sendable {
  /// Default value. This value is unused.
  case unspecified
  /// A critical vulnerability is easily discoverable by an external actor,
  /// exploitable, and results in the direct ability to execute arbitrary code,
  /// exfiltrate data, and otherwise gain additional access and privileges to
  /// cloud resources and workloads. Examples include publicly accessible
  /// unprotected user data and public SSH access with weak or no
  /// passwords.
  ///
  /// A critical threat is a threat that can access, modify, or delete data or
  /// execute unauthorized code within existing resources.
  case critical
  /// A high-risk vulnerability can be easily discovered and exploited in
  /// combination with other vulnerabilities to gain direct access and
  /// the ability to execute arbitrary code, exfiltrate data, and otherwise
  /// gain additional access and privileges to cloud resources and workloads.
  /// An example is a database with weak or no passwords that is only
  /// accessible internally. This database could easily be compromised by an
  /// actor that had access to the internal network.
  ///
  /// A high-risk threat is a threat that can create new computational
  /// resources in an environment but can't access data or execute code in
  /// existing resources.
  case high
  /// A medium-risk vulnerability can be used by an actor to gain access to
  /// resources or privileges that enable them to eventually (through multiple
  /// steps or a complex exploit) gain access and the ability to execute
  /// arbitrary code or exfiltrate data. An example is a service account with
  /// access to more projects than it should have. If an actor gains access to
  /// the service account, they could potentially use that access to manipulate
  /// a project the service account was not intended to.
  ///
  /// A medium-risk threat can cause operational impact but might not
  /// access data or execute unauthorized code.
  case medium
  /// A low-risk vulnerability hampers a security organization's ability to
  /// detect vulnerabilities or active threats in their deployment, or prevents
  /// the root cause investigation of security issues. An example is monitoring
  /// and logs being disabled for resource configurations and access.
  ///
  /// A low-risk threat is a threat that has obtained minimal access to an
  /// environment but can't access data, execute code, or create resources.
  case low
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific integer values in this case;
  ///   future releases may promote them to named enum cases.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown value is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  ///
  /// - Warning: Do not pattern-match specific string literals in this case;
  ///   future releases may promote them to named enum cases.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .critical: return 1
    case .high: return 2
    case .medium: return 3
    case .low: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "SEVERITY_UNSPECIFIED"
    case .critical: return "CRITICAL"
    case .high: return "HIGH"
    case .medium: return "MEDIUM"
    case .low: return "LOW"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Severity/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "SEVERITY_UNSPECIFIED": self = .unspecified
    case "CRITICAL": self = .critical
    case "HIGH": self = .high
    case "MEDIUM": self = .medium
    case "LOW": self = .low
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Severity/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .critical
    case 2: self = .high
    case 3: self = .medium
    case 4: self = .low
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode("SEVERITY_UNSPECIFIED")
    case .critical: return try container.encode("CRITICAL")
    case .high: return try container.encode("HIGH")
    case .medium: return try container.encode("MEDIUM")
    case .low: return try container.encode("LOW")
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
