// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The configuration that's required to create a target resource.
public struct TargetResourceCreationConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The configuration that's required to create the target resource.
  public var resourceCreationConfig: ResourceCreationConfigOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `TargetResourceCreationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TargetResourceCreationConfig().with { $0.folderCreationConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let folderCreationConfig = CodingKeys(stringValue: "folderCreationConfig")
    static let projectCreationConfig = CodingKeys(stringValue: "projectCreationConfig")

    static let _knownKeys: Set<Swift.String> = [
      "folderCreationConfig",
      "projectCreationConfig",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var resourceCreationConfig: ResourceCreationConfigOneOf? = nil
    let resourceCreationConfigCheckAndSet = {
      if resourceCreationConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'resourceCreationConfig'"))
      }
      resourceCreationConfig = $0
    }
    if let folderCreationConfig = try container.decodeIfPresent(
      FolderCreationConfig.self, forKey: .folderCreationConfig)
    {
      try resourceCreationConfigCheckAndSet(.folderCreationConfig(folderCreationConfig))
    }
    if let projectCreationConfig = try container.decodeIfPresent(
      ProjectCreationConfig.self, forKey: .projectCreationConfig)
    {
      try resourceCreationConfigCheckAndSet(.projectCreationConfig(projectCreationConfig))
    }
    self.resourceCreationConfig = resourceCreationConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.resourceCreationConfig {
      switch choice {
      case .folderCreationConfig(let value):
        try container.encode(value, forKey: .folderCreationConfig)
      case .projectCreationConfig(let value):
        try container.encode(value, forKey: .projectCreationConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration that's required to create the target resource.
  public enum ResourceCreationConfigOneOf: Codable, Equatable, Sendable {
    /// Optional. The configuration that's required to create a folder.
    indirect case folderCreationConfig(FolderCreationConfig)
    /// Optional. The configuration that's required to create a project.
    indirect case projectCreationConfig(ProjectCreationConfig)
  }

  /// The type URL for `TargetResourceCreationConfig`: `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceCreationConfig"`.
  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceCreationConfig"
  }

  /// Initialize an instance of `TargetResourceCreationConfig` by unpacking from a `GoogleWKT.WKTAny`.
  ///
  /// - Parameter any: The `GoogleWKT.WKTAny` instance to unpack.
  /// - Throws: An error if the type URL in `any` does not match `"type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.TargetResourceCreationConfig"`,
  ///   or if deserialization fails.
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }

  /// Packs this `TargetResourceCreationConfig` into a `GoogleWKT.WKTStruct` representation.
  ///
  /// - Throws: An error if serialization fails.
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
