// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The validation of the parameter.
public struct Validation: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Defines validators for parameter values.
  public var constraint: ConstraintOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Validation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Validation().with { $0.allowedValues = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let allowedValues = CodingKeys(stringValue: "allowedValues")
    static let intRange = CodingKeys(stringValue: "intRange")
    static let regexpPattern = CodingKeys(stringValue: "regexpPattern")

    static let _knownKeys: Set<Swift.String> = [
      "allowedValues",
      "intRange",
      "regexpPattern",
    ]
  }

  public init(from decoder: any Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var constraint: ConstraintOneOf? = nil
    let constraintCheckAndSet = {
      if constraint != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'constraint'"))
      }
      constraint = $0
    }
    if let allowedValues = try container.decodeIfPresent(AllowedValues.self, forKey: .allowedValues)
    {
      try constraintCheckAndSet(.allowedValues(allowedValues))
    }
    if let intRange = try container.decodeIfPresent(IntRange.self, forKey: .intRange) {
      try constraintCheckAndSet(.intRange(intRange))
    }
    if let regexpPattern = try container.decodeIfPresent(RegexpPattern.self, forKey: .regexpPattern)
    {
      try constraintCheckAndSet(.regexpPattern(regexpPattern))
    }
    self.constraint = constraint
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: any Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.constraint {
      switch choice {
      case .allowedValues(let value):
        try container.encode(value, forKey: .allowedValues)
      case .intRange(let value):
        try container.encode(value, forKey: .intRange)
      case .regexpPattern(let value):
        try container.encode(value, forKey: .regexpPattern)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Defines validators for parameter values.
  public enum ConstraintOneOf: Codable, Equatable, Sendable {
    /// The permitted set of values for the parameter.
    indirect case allowedValues(AllowedValues)
    /// The permitted range for numeric parameters.
    indirect case intRange(IntRange)
    /// The regular expression for string parameters.
    indirect case regexpPattern(RegexpPattern)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.cloudsecuritycompliance.v1.Validation"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
